Repository modxcms/revolution, pull requests merged in 2018-09, with the labels that each got.

#14079 PhpDoc
  core/model/modx/modx.class.php
Labels: pr-state/ready-for-merging

#14083 [ReUp] fix manager header height on resize
  _build/templates/default/sass/_navbar.scss
Labels: area-ux/ui, bug, pr-state/ready-for-merging

#14092 Set the min-height of a x-combo-list-item
  _build/templates/default/sass/_colors-and-vars.scss
  _build/templates/default/sass/_forms.scss
Labels: area-ux/ui, bug, pr-state/ready-for-merging

#14091 Remove Bower from _build
  _build/templates/default/bower.json
  _build/templates/default/gruntfile.js
  _build/templates/default/package.json
Labels: area-core, bug, pr-state/review-needed
