Repository modxcms/revolution, pull requests merged in 2018-12, with the labels that each got.

#14160 Make the flat file processor deprecated message more useful
  core/model/modx/modprocessor.class.php
Labels: enhancement, pr-state/ready-for-merging

#14181 Add Slack to the list of support channels in composer.json
  composer.json
Labels: enhancement, pr-state/ready-for-merging

#14180 Fixed some minor npm audit issues
  _build/templates/default/package-lock.json
  _build/templates/default/package.json
Labels: enhancement, pr-state/ready-for-merging

#14195 Recognize error_log_file* settings when switching contexts
  core/model/modx/modx.class.php
Labels: pr-state/ready-for-merging

#14191 Fix "undefined" text in Trash manager button tooltip
  manager/templates/default/header.tpl
Labels: area-ux/ui, bug, pr-state/ready-for-merging

#14133 Remove outdated classes for converting evo tags to revo
  core/model/modx/modparser095.class.php
  core/model/modx/modtranslate095.class.php
  core/model/modx/transport/modtranslator.class.php
Labels: area-core, enhancement, pr-state/review-needed

#14196 Use a secure and not spammable example hostname
  ht.access
Labels: area-security, bug, pr-state/ready-for-merging

#14199 Fixed position of context menu in the media browser
  manager/assets/modext/core/modx.view.js
Labels: area-ux/ui, bug, pr-state/ready-for-merging

#14222 Use the right table name when fetching the MODX package providers
  core/model/modx/processors/workspace/providers/getlist.class.php
Labels: area-core, pr-state/ready-for-merging

#14224 Apply Form Customization rules for TV's when a wildcard action is used
  core/model/modx/modtemplatevar.class.php
Labels: area-form_customization, pr-state/ready-for-merging
