Repository modxcms/revolution, pull requests merged in 2018-10, with the labels that each got.

#14108 Prevent an infinite loop in sendErrorPage()
  core/model/modx/modx.class.php
Labels: area-core, bug, pr-state/ready-for-merging

#14038 Fix for "Invalid relative media source path shows root path contents"
  core/model/modx/sources/modfilemediasource.class.php
Labels: area-core, bug, pr-state/ready-for-merging, priority-2-high

#14054 Delete files in Media Browser with '&' in the file name
  core/model/modx/processors/browser/file/remove.class.php
Labels: pr-state/ready-for-merging

#14076 Fixing Double-click of image in Media Browser goes to blank page
  manager/assets/modext/widgets/media/browser.js
  manager/assets/modext/widgets/media/modx.browser.js
Labels: area-ux/ui, bug, pr-state/ready-for-merging

#14066 Fix uninstall errors
  core/model/modx/processors/workspace/packages/remove.class.php
  core/model/modx/transport/modtransportpackage.class.php
Labels: area-core, bug, pr-state/ready-for-merging

#14069 Applied unused before configuration options with charset and collation during database creation
  setup/includes/tables_create.php
Labels: area-core, pr-state/ready-for-merging

#14040 Hide Input Option Values for TV types where this is useless
  manager/assets/modext/widgets/element/modx.panel.tv.js
  manager/templates/default/element/tv/renders/inputproperties/date.tpl
  manager/templates/default/element/tv/renders/inputproperties/email.tpl
  manager/templates/default/element/tv/renders/inputproperties/file.tpl
  manager/templates/default/element/tv/renders/inputproperties/image.tpl
  manager/templates/default/element/tv/renders/inputproperties/number.tpl
  manager/templates/default/element/tv/renders/inputproperties/resourcelist.tpl
  manager/templates/default/element/tv/renders/inputproperties/text.tpl
  manager/templates/default/element/tv/renders/inputproperties/textarea.tpl
Labels: area-ux/ui, enhancement, pr-state/ready-for-merging

#14124 Fixed the name of system setting about allowing or not eval in TV
  core/lexicon/en/setting.inc.php
Labels: area-i18n/l10n, bug, pr-state/ready-for-merging
