Repository modxcms/revolution, pull requests merged in 2018-06, with the labels that each got.

#13916 Fix Regex validation for TV's of the input type "Text"
  manager/templates/default/element/tv/renders/input/textbox.tpl
Labels: area-core, bug, priority-2-high

#13915 Option to supply waitMsg on submit in window
  manager/assets/modext/modx.jsgrps-min.js
Labels: area-ux/ui, bug, priority-3-low

#13882 Add template icon for resources in search results.
  core/model/modx/processors/search/search.class.php
Labels: state/ready-for-merging

#13588 Add system setting to clear resource cache partially for xPDOFileCache
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/model/modx/modcachemanager.class.php
Labels: area-core, enhancement, state/in-progress

#13936 Fixed conflict marks after merging 2.x into 3.x
  core/lexicon/be/default.inc.php
  core/lexicon/ru/setting.inc.php
Labels: bug, priority-2-high
