Repository modxcms/revolution, pull requests merged in 2018-08, with the labels that each got.

#14022 Remove non-functional cache_disabled system setting
  _build/data/transport.core.system_settings.php
  _build/test/revo_install.sample.xml
  core/docs/config.inc.tpl
  core/lexicon/en/setting.inc.php
  index.php
  setup/cli-install.php
  setup/config.dist.new.xml
  setup/config.dist.upgrade-advanced.xml
  setup/includes/config/modconfigreader.class.php
  setup/includes/config/modevolutionconfigreader.class.php
  setup/includes/config/modrevolutionconfigreader.class.php
  setup/includes/upgrades/common/2.7-remove-cache-disabled.php
  setup/includes/upgrades/mysql/2.7.0-pl.php
  setup/includes/upgrades/sqlsrv/2.7.0-pl.php
Labels: area-core, priority-3-low, state/ready-for-merging

#14039 Do not give TVs with output type as HTML an ID if no ID is sat
  core/model/modx/processors/element/tv/renders/web/output/htmltag.class.php
Labels: pr-state/ready-for-merging

#13930 Adds a RewriteRule to the example htaccess
  ht.access
Labels: area-security, pr-state/ready-for-merging

#14055 New static Slack badge in the Readme
  README.md
Labels: pr-state/ready-for-merging

#14052 Fixing images escaping their container in media browser
  _build/templates/default/sass/_browser.scss
Labels: pr-state/ready-for-merging

#14065 changed resource query to count children via subqueries
  core/model/modx/processors/resource/getnodes.class.php
Labels: area-core, enhancement, pr-state/ready-for-merging
