Repository modxcms/revolution, pull requests merged in 2019-04, with the labels that each got.

#14559 Fix resource checkbox animation
  _build/templates/default/sass/_forms.scss
Labels: area-ux/ui, pr-state/ready-for-merging

#14477 Update phpThumb to fix an issue with converting images
  core/model/phpthumb/phpthumb.class.php
Labels: area-core, pr-state/ready-for-merging

#14567 Increase width on modx-leftbar, prevents trash tab from hiding
  _build/templates/default/sass/_navbar.scss
  manager/assets/modext/core/modx.layout.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14496 Change the indents on the System Info page
  _build/templates/default/sass/_dashboard.scss
Labels: area-ux/ui, pr-state/ready-for-merging

#14488 Make MODX 3 require at least PHP 7.0
  .travis.yml
  composer.json
  manager/index.php
  setup/includes/test/modinstalltest.class.php
Labels: area-core, enhancement, pr-state/ready-for-merging
