Repository modxcms/revolution, pull requests merged in 2019-02, with the labels that each got.

#14203 Fix duplicating static templates, snippets etc. with an empty category
  manager/assets/modext/sections/element/chunk/update.js
  manager/assets/modext/sections/element/plugin/update.js
  manager/assets/modext/sections/element/snippet/update.js
  manager/assets/modext/sections/element/template/update.js
  manager/assets/modext/sections/element/tv/update.js
Labels: area-core, bug, pr-state/ready-for-merging

#14317 Fixed issues with tab width and very long strings in the tabs
  _build/templates/default/sass/_tabs.scss
Labels: area-ux/ui, bug, pr-state/ready-for-merging

#14329 Fix issue with resourcelist preventing parents from working correctly (Fixes #14207)
  core/model/modx/processors/element/tv/renders/mgr/input/resourcelist.class.php
Labels: area-core, bug, pr-state/ready-for-merging

#14324 Add favicon to manager in System settings
  _build/data/transport.core.system_settings.php
  manager/favicon.ico
Labels: enhancement, pr-state/ready-for-merging

#14318 Clarify the description of adding icons to templates
  core/lexicon/en/template.inc.php
Labels: area-ux/ui, enhancement, pr-state/ready-for-merging

#14336 Fix CVE-2018-17556
  manager/assets/modext/widgets/source/modx.panel.sources.js
Labels: area-security, enhancement, pr-state/ready-for-merging

#14325 Change the Manager date and time format after a clean installation.
  _build/data/transport.core.system_settings.php
Labels: area-ux/ui, enhancement, pr-state/ready-for-merging

#14361 Restore html in resource tree (#14358) while preserving XSS protections by default
  core/model/modx/processors/resource/getnodes.class.php
  manager/assets/modext/util/utilities.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
  manager/assets/modext/widgets/resource/modx.tree.resource.simple.js
  manager/assets/modext/widgets/system/modx.tree.menu.js
Labels: area-security

#14347 Fix the composer phpunit script
  composer.json
Labels: area-core, pr-state/ready-for-merging

#14359 Handle deprecated $type and $responseCode parameters in $modx->sendRedirect
  core/model/modx/modresponse.class.php
  core/model/modx/modx.class.php
Labels: area-core, bug, pr-state/ready-for-merging

#14348 Using cltr/cmd and click will open the url in a new tab/window again
  manager/assets/modext/core/modx.layout.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14379 Fix watch grunt task where used outdated and already removed growl plugin
  _build/templates/default/gruntfile.js
Labels: bug, pr-state/ready-for-merging

#14392 Change the RSS feed URLs to HTTPS
  _build/data/transport.core.system_settings.php
  setup/includes/upgrades/common/2.7.2-feed-modx-https.php
  setup/includes/upgrades/mysql/2.7.2-pl.php
  setup/includes/upgrades/sqlsrv/2.7.2-pl.php
Labels: area-security, pr-state/ready-for-merging

#14403 Typos in upgrade scripts
  setup/includes/upgrades/mysql/2.4.1-pl.php
  setup/includes/upgrades/mysql/2.5.0-pl.php
  setup/includes/upgrades/mysql/2.5.5-pl.php
  setup/includes/upgrades/mysql/2.7.0-pl.php
  setup/includes/upgrades/sqlsrv/2.5.0-pl.php
  setup/includes/upgrades/sqlsrv/2.5.5-pl.php
Labels: area-setup, pr-state/ready-for-merging

#14416 Remove manager/min folder from sources
  manager/min/README.txt
  manager/min/groupsConfig.php
  manager/min/ht.access
  manager/min/index.php
  manager/min/lib/FirePHP.php
  manager/min/lib/HTTP/ConditionalGet.php
  manager/min/lib/HTTP/Encoder.php
  manager/min/lib/JSMin.php
  manager/min/lib/JSMinPlus.php
  manager/min/lib/Minify.php
  manager/min/lib/Minify/Build.php
  manager/min/lib/Minify/CSS.php
  manager/min/lib/Minify/CSS/Compressor.php
  manager/min/lib/Minify/CSS/UriRewriter.php
  manager/min/lib/Minify/Cache/APC.php
  manager/min/lib/Minify/Cache/File.php
  manager/min/lib/Minify/Cache/Memcache.php
  manager/min/lib/Minify/Cache/ZendPlatform.php
  manager/min/lib/Minify/CommentPreserver.php
  manager/min/lib/Minify/Controller/Base.php
  manager/min/lib/Minify/Controller/Files.php
  manager/min/lib/Minify/Controller/Groups.php
  manager/min/lib/Minify/Controller/MinApp.php
  manager/min/lib/Minify/Controller/Page.php
  manager/min/lib/Minify/Controller/Version1.php
  manager/min/lib/Minify/DebugDetector.php
  manager/min/lib/Minify/HTML.php
  manager/min/lib/Minify/HTML/Helper.php
  manager/min/lib/Minify/ImportProcessor.php
  manager/min/lib/Minify/JS/ClosureCompiler.php
  manager/min/lib/Minify/Lines.php
  manager/min/lib/Minify/Logger.php
  manager/min/lib/Minify/Packer.php
  manager/min/lib/Minify/Source.php
  manager/min/lib/Minify/YUI/CssCompressor.java
  manager/min/lib/Minify/YUI/CssCompressor.php
  manager/min/lib/Minify/YUICompressor.php
  manager/min/lib/MrClay/Cli.php
  manager/min/lib/MrClay/Cli/Arg.php
  manager/min/utils.php
Labels: area-core, bug, pr-state/ready-for-merging

#14414 Prevent Google Chrome translations from the admin panel
  manager/templates/default/header.tpl
Labels: area-ux/ui, pr-state/ready-for-merging
