Repository modxcms/revolution, pull requests merged in 2019-03, with the labels that each got.

#14421 Update editorconfig
  .editorconfig
Labels: area-core, enhancement, pr-state/ready-for-merging

#14425 Load all mgr permissions at once to MODx.perm
  core/model/modx/processors/system/config.js.class.php
Labels: area-core, pr-state/ready-for-merging

#14427 Changes the font stack for displaying code
  _build/templates/default/sass/_colors-and-vars.scss
Labels: area-ux/ui, pr-state/ready-for-merging

#14397 Fix connector deprecated each()
  connectors/lang.js.php
Labels: area-core, bug, pr-state/ready-for-merging

#14396 Don't execute the upgrade script for the last installed version again
  setup/includes/modinstallversion.class.php
Labels: area-setup, bug, pr-state/ready-for-merging

#14413 Change icon for descending sort order
  manager/templates/default/images/modx-theme/grid/sort_desc.gif
Labels: area-ux/ui, pr-state/ready-for-merging

#14401 Fix, added escape field content for tooltip
  core/model/modx/processors/resource/trash/getlist.class.php
  manager/assets/modext/widgets/resource/modx.grid.trash.js
Labels: area-security, bug, pr-state/ready-for-merging

#14443 Placed the changelog entries under the right release
  core/docs/changelog.txt
Labels: area-core, pr-state/ready-for-merging

#14441 Fix friendly_alias_realtime setting not working
  manager/assets/modext/widgets/resource/modx.panel.resource.js
Labels: area-core, bug, pr-state/ready-for-merging

#14439 Fix connector deprecated each()
  connectors/lang.js.php
Labels: area-core, bug, pr-state/ready-for-merging

#14461 Restore PHP 5.3 compatibility (while dreaming of 7.1)
  core/model/modx/modx.class.php
Labels: pr-state/ready-for-merging

#14446 Fix saving the content of Symlink/Weblink/Static resources
  manager/assets/modext/widgets/resource/modx.panel.resource.js
  manager/assets/modext/widgets/resource/modx.panel.resource.static.js
  manager/assets/modext/widgets/resource/modx.panel.resource.symlink.js
  manager/assets/modext/widgets/resource/modx.panel.resource.weblink.js
Labels: area-core, pr-state/ready-for-merging

#14301 Bugfix for thumbnails not rendering for s3 image URL's with spaces.
  core/model/phpthumb/modphpthumb.class.php
  core/model/phpthumb/phpthumb.class.php
Labels: area-core, bug, pr-state/ready-for-merging

#14415 Change System font stack
  _build/templates/default/sass/_colors-and-vars.scss
Labels: area-ux/ui, enhancement, pr-state/ready-for-merging

#14451 Adds check for tree render on Access Control Lists page
  manager/assets/modext/widgets/security/modx.panel.groups.roles.js
Labels: area-core, bug, pr-state/ready-for-merging

#14328 Change default automatic_template_assignment, tree node fallback, and preserve_menuindex
  _build/data/transport.core.system_settings.php
Labels: area-setup, enhancement, pr-state/ready-for-merging

#14360 Minor changes in Media Source Browser
  core/lexicon/en/file.inc.php
  manager/assets/modext/widgets/media/modx.browser.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14305 Return empty string for empty xml tag in modRestService
  core/model/modx/rest/modrestservice.class.php
Labels: area-core, enhancement, pr-state/ready-for-merging

#14466 [ReUp] Fix image content being too wide for the dashboard widget.
  _build/templates/default/sass/_dashboard.scss
Labels: area-ux/ui, pr-state/ready-for-merging

#14480 Remove min folder from core transport package builder
  _build/transport.core.php
Labels: pr-state/ready-for-merging

#14478 Login lexicon - Good Night changed to Good Evening
  core/lexicon/en/login.inc.php
Labels: area-ux/ui, pr-state/ready-for-merging

#14465 Fix disappearing ID when typing element name or resource pagetitle
  manager/assets/modext/widgets/element/modx.panel.chunk.js
  manager/assets/modext/widgets/element/modx.panel.plugin.js
  manager/assets/modext/widgets/element/modx.panel.snippet.js
  manager/assets/modext/widgets/element/modx.panel.template.js
  manager/assets/modext/widgets/element/modx.panel.tv.js
  manager/assets/modext/widgets/resource/modx.panel.resource.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14476 Update README.md
  README.md
Labels: area-core, pr-state/ready-for-merging
