Repository modxcms/revolution, pull requests merged in 2019-07, with the labels that each got.

#14606 Widen searchbar
  _build/templates/default/sass/_uberbar.scss
  manager/assets/modext/widgets/core/modx.searchbar.js
Labels: pr-state/ready-for-merging

#14631 Forward port of PR 14609
  core/src/Revolution/Processors/Resource/Create.php
  core/src/Revolution/Processors/Resource/Update.php
Labels: area-core, pr-state/review-needed

#14626 Remove negative margin top
  _build/templates/default/sass/_browser.scss
Labels: area-ux/ui, pr-state/review-needed

#14494 Fix for undefined constant IMG_WEBP
  core/model/phpthumb/modphpthumb.class.php
Labels: area-core, pr-state/ready-for-merging

#14644 Fix the create new Content Type button
  manager/assets/modext/widgets/system/modx.grid.content.type.js
Labels: 3.x refactor, pr-state/review-needed

#14645 Make file editing work again
  manager/controllers/default/system/file/create.class.php
  manager/controllers/default/system/file/edit.class.php
Labels: 3.x refactor, pr-state/review-needed

#14646 Show additional properties again when creating a TV
  core/src/Revolution/Processors/Element/TemplateVar/Renders/GetInputProperties.php
Labels: 3.x refactor, pr-state/review-needed

#14647 Fix for undefined constant IMG_WEBP
  core/src/Revolution/modPhpThumb.php
Labels: area-core, pr-state/review-needed

#14643 Also check for scheme value as string
  core/model/modx/modcontext.class.php
Labels: pr-state/review-needed
