Repository modxcms/revolution, pull requests merged in 2019-01, with the labels that each got.

#14050 Add a reloadContext option to modResourceUpdateProcessor
  core/model/modx/processors/resource/update.class.php
Labels: pr-state/ready-for-merging

#14217 Add icons to elements in elements tree
  core/model/modx/processors/element/getnodes.class.php
Labels: area-ux/ui, pr-state/ready-for-merging

#14198 Add modifiers to get information from filepath: dirname, basename, fi…
  _build/test/Tests/Model/Filters/modOutputFilterTest.php
  core/model/modx/filters/modoutputfilter.class.php
Labels: area-core, enhancement, pr-state/ready-for-merging

#14234 Make working Preview menu option in the recent edited resources widget
  core/model/modx/processors/security/user/getrecentlyeditedresources.class.php
  manager/assets/modext/widgets/security/modx.grid.user.recent.resource.js
Labels: bug, pr-state/ready-for-merging

#14225 [3.x] Clean up some styles, less borders -> more depth, better emphasis
  _build/templates/default/sass/_buttons.scss
  _build/templates/default/sass/_colors-and-vars.scss
  _build/templates/default/sass/_navbar.scss
  _build/templates/default/sass/_tabs.scss
  _build/templates/default/sass/_tree.scss
  _build/templates/default/sass/index.scss
  manager/assets/modext/core/modx.layout.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14162 Improve deprecated notice for "Old modTemplateVar getRender input"
  core/model/modx/modtemplatevar.class.php
Labels: enhancement, pr-state/ready-for-merging

#14258 Fix position .action-buttons
  _build/templates/default/sass/_dashboard.scss
Labels: area-ux/ui, bug

#14263 Fix escaping for image template variables #12126
  manager/templates/default/element/tv/renders/input/image.tpl
Labels: area-core, bug, pr-state/ready-for-merging

#14228 Don't remove static files if automated static files are turned off
  core/model/modx/processors/element/remove.class.php
Labels: area-core, bug, pr-state/ready-for-merging

#14261 Fix checkDownloadedDependencies query
  core/model/modx/transport/modtransportpackage.class.php
Labels: area-core, bug, pr-state/ready-for-merging

#14252 Remove support for "Uploadable Flash Types"
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/model/modx/sources/modmediasource.class.php
  setup/includes/upgrades/common/3.0.0-remove-upload-flash-system-setting.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: area-core, pr-state/ready-for-merging

#14276 Enhance the error message of a wrong MODX_CORE_PATH
  setup/templates/findcore.php
Labels: area-setup, enhancement, pr-state/ready-for-merging

#14274 Fix Fatal error: Uncaught Error: Class 'xPDO' not found #14241
  setup/includes/drivers/modinstalldriver_mysql.class.php
Labels: area-core, pr-state/ready-for-merging

#14282 Fix position icon x-btn-arrow
  _build/templates/default/sass/components/_secondary-button.scss
Labels: area-ux/ui, pr-state/ready-for-merging

#14284 Fix edit empty files from tree
  core/model/modx/modfilehandler.class.php
Labels: area-core, bug, pr-state/ready-for-merging

#14272 Fixed correct translation display for [[+type]] in confirm delete popup window
  manager/assets/modext/widgets/element/modx.tree.element.js
Labels: area-ux/ui, bug, pr-state/ready-for-merging

#14260 Bugfix for transport resolution, if the package is not found on the current provider
  core/model/modx/transport/modtransportpackage.class.php
Labels: area-core, bug, pr-state/ready-for-merging

#14278 Don't remove the trailing slash when redirecting to the manager after logging in
  manager/controllers/default/security/login.class.php
Labels: area-core, pr-state/ready-for-merging

#14287 Fix empty Constraint column in FC if constraint value is zero
  core/model/modx/processors/security/forms/set/getlist.class.php
Labels: area-core, pr-state/ready-for-merging

#14290 Fixed empty date TVs can be saved even if "allow blank" is set to false #12302
  manager/assets/modext/util/datetime.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14205 Return the category path with an id request
  core/model/modx/processors/element/category/getlist.class.php
Labels: area-core, bug, pr-state/ready-for-merging

#14243 Added physical links to the href attribute for elements in the tree
  manager/assets/modext/util/utilities.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14237 Update copyright to the present
  COPYRIGHT
  _build/docs/themes/modx/template.xml
  setup/templates/base_template.tpl
Labels: pr-state/ready-for-merging

#14249 Improve description of the system setting user_settings_desc to clarify meaning
  core/lexicon/en/user.inc.php
Labels: enhancement, pr-state/ready-for-merging

#14281 Fixed bug with unexpected incremented TV ranks in Form Customization
  core/model/modx/modformcustomizationset.class.php
Labels: area-form_customization, pr-state/ready-for-merging

#14150 Add required and suggested PHP extensions to composer.json
  .travis.yml
Labels: enhancement, pr-state/ready-for-merging

#14215 Disabled Gravatar by default for new installations
  _build/data/transport.core.system_settings.php
Labels: pr-state/ready-for-merging

#14295 Fix context menu position on user page "Access Permissions" tab
  manager/assets/modext/widgets/security/modx.grid.user.group.js
Labels: area-ux/ui, bug, pr-state/ready-for-merging

#14298 Fix position slide-in/slide-out button of Resource tree
  _build/templates/default/sass/_tree.scss
Labels: area-ux/ui, bug, pr-state/ready-for-merging

#14271 Fix Width Manager Sidebar - is increased after browser resize #13954
  _build/templates/default/sass/_navbar.scss
Labels: area-ux/ui, bug, pr-state/ready-for-merging

#14304 Check config in root for search moved core path
  setup/includes/config.core.php
Labels: area-setup, enhancement, pr-state/ready-for-merging

#14259 Fix margin .modx-page-header
  _build/templates/default/sass/index.scss
Labels: area-ux/ui, enhancement

#14250 Insert TV-tab before Settings-tab in resource editing form
  manager/assets/modext/widgets/resource/modx.panel.resource.js
Labels: area-ux/ui, pr-state/review-needed

#14210 Don't include the resource ID in real time aliases
  manager/assets/modext/widgets/resource/modx.panel.resource.js
Labels: area-ux/ui, pr-state/ready-for-merging
