Repository modxcms/revolution, pull requests merged in 2019-05, with the labels that each got.

#14502 Removed dots at the end of descriptions of menu items
  core/lexicon/en/topmenu.inc.php
Labels: area-i18n/l10n, pr-state/ready-for-merging

#14553 Added styles for scroll
  _build/templates/default/sass/index.scss
Labels: area-ux/ui, pr-state/ready-for-merging

#14523 Fixed #14448 (Spaces before or after search word distort the result)
  core/model/modx/processors/search/search.class.php
Labels: pr-state/ready-for-merging

#14525 Add notification of successful database operation on System Info > Database tables
  core/lexicon/en/system_info.inc.php
  manager/assets/modext/widgets/system/mysql/modx.grid.databasetables.js
  manager/assets/modext/widgets/system/sqlsrv/modx.grid.databasetables.js
Labels: area-core, pr-state/ready-for-merging

#14528 Fixes media sources no-icon in media browser
  manager/assets/modext/widgets/media/modx.browser.js
Labels: pr-state/ready-for-merging

#14557 Minor change style for dashboards
  _build/templates/default/sass/_dashboard.scss
  manager/templates/default/dashboard/recentlyeditedresources.tpl
Labels: area-ux/ui, pr-state/ready-for-merging

#14463 Using a single pattern for elements action buttons like a resource
  manager/assets/modext/sections/element/chunk/create.js
  manager/assets/modext/sections/element/chunk/update.js
  manager/assets/modext/sections/element/plugin/create.js
  manager/assets/modext/sections/element/plugin/update.js
  manager/assets/modext/sections/element/snippet/create.js
  manager/assets/modext/sections/element/snippet/update.js
  manager/assets/modext/sections/element/template/create.js
  manager/assets/modext/sections/element/template/update.js
  manager/assets/modext/sections/element/tv/create.js
  manager/assets/modext/sections/element/tv/update.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14522 Automatically marking required fields by an asterisk
  manager/templates/default/css/index.css
Labels: pr-state/ready-for-merging

#14533 Added an icon in the menu tree
  manager/assets/modext/widgets/system/modx.tree.menu.js
Labels: pr-state/ready-for-merging
