Repository modxcms/revolution, pull requests merged in 2019-06, with the labels that each got.

#14612 Fixed missed FQCN of modRestResponse class
  core/src/Revolution/Rest/modRestClient.php
Labels: pr-state/review-needed

#14613 Fixed missed imports for modSystemEvent class
  manager/controllers/default/security/user/create.class.php
  manager/controllers/default/security/user/update.class.php
Labels: pr-state/review-needed

#14543 Fixed bug for checking the table prefix while installing MODX
  setup/processors/database/collation.php
  setup/processors/database/connection.php
Labels: pr-state/ready-for-merging

#14584 Add new rule for .scss in editorconfig
  .editorconfig
Labels: pr-state/ready-for-merging, pr-state/review-needed

#14607 Add widget welcome dashboard changes
  manager/assets/modext/widgets/modx.panel.welcome.js
Labels: pr-state/ready-for-merging
