Repository modxcms/revolution, pull requests merged in 2019-12, with the labels that each got.

#14869 [3.x] Remove support for flat file processors
  core/src/Revolution/Processors/DeprecatedProcessor.php
  core/src/Revolution/modX.php
Labels: pr-state/review-needed

#14871 Fix processors path for setting an access to namespace
  core/src/Revolution/Processors/Security/Access/UserGroup/AccessNamespace/GetList.php
  manager/assets/modext/widgets/security/modx.grid.user.group.namespace.js
Labels: bug

#14877 Removed unused system settings for "System and Server" section
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  setup/includes/upgrades/common/3.0.0-cleanup-system-settings.php
Labels: pr-state/ready-for-merging

#14873 Format timestamp to date & time in edit file panel
  manager/assets/modext/sections/system/file/edit.js
  manager/assets/modext/util/utilities.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14872 Fix sizing of the actions column
  manager/assets/modext/widgets/core/modx.grid.js
Labels: pr-state/ready-for-merging

#14888 Fix saving a form customisation profile, plus fix XSS in profile name
  manager/assets/modext/widgets/fc/modx.panel.fcprofile.js
Labels: pr-state/review-needed, priority-2-high

#14889 Fix deprecation warnings on curly brace string offset access syntax
  core/docs/changelog.txt
  core/src/Revolution/modResource.php
  core/src/Revolution/modStaticResource.php
Labels: bug

#14913 Fix unit tests depending on deprecated classes being loaded
  _build/test/MODxTestHarness.php
  manager/controllers/default/dashboard/widget.updates.php
  manager/controllers/default/header.php
  manager/controllers/default/resource/create.class.php
  manager/controllers/default/resource/data.class.php
Labels: 3.x refactor, area-core, bug

#14898 Clean up legacy core/model files
  setup/includes/upgrades/common/3.0-cleanup-files.php
Labels: 3.x refactor, area-setup, pr-state/review-needed

#14911 Fix click handler on grid
  manager/assets/modext/widgets/core/modx.grid.js
Labels: 3.x refactor, area-ux/ui, bug, priority-1-urgent

#14920 Add a DI container and allow namespaces to define a bootstrap.php
  composer.json
  core/.gitignore
  core/src/Revolution/Services/Container.php
  core/src/Revolution/Services/ContainerException.php
  core/src/Revolution/Services/NotFoundException.php
  core/src/Revolution/modX.php
Labels: 3.x refactor, area-core, feature, needs documentation, pr-state/review-needed, priority-1-urgent

#14921 Call getInstance instead of creating directly new instance of processor
  core/src/Revolution/modX.php
Labels: area-core, bug, priority-1-urgent

#14912 Move deprecated class_aliases out of composer and clean up entry points
  composer.json
  connectors/index.php
  core/src/Revolution/modX.php
  index.php
  manager/index.php
Labels: 3.x refactor, area-core, bug, pr-state/review-needed, priority-1-urgent

#14895 Remove and clean up unused MODx.grid components
  manager/assets/modext/widgets/resource/modx.grid.resource.security.js
  manager/assets/modext/widgets/security/modx.grid.role.user.js
  manager/assets/modext/workspace/lexicon/language.grid.js
  manager/assets/modext/workspace/lexicon/lexicon.topic.grid.js
  setup/includes/upgrades/common/3.0-cleanup-files.php
Labels: area-core, needs documentation, pr-state/review-needed

#14894 Deleting resource with new switch (checkbox) shows duplicate in tree
  manager/assets/modext/widgets/resource/modx.panel.resource.js
Labels: area-ux/ui, pr-state/review-needed

#14896 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: pr-state/ready-for-merging
