Repository modxcms/revolution, pull requests merged in 2019-08, with the labels that each got.

#14661 Deleted an unnecessary file /header.tpl
  header.tpl
Labels: 3.x refactor, pr-state/ready-for-merging

#14657 Fix a potential PHP 7.4/8.0 compatibility issue
  manager/controllers/default/resource/update.class.php
Labels: area-core, pr-state/review-needed

#14665 Update phpthumb.class.php
  core/model/modx/processors/system/phpthumb.class.php
Labels: pr-state/ready-for-merging

#14656 Fix a potential PHP 7.4/8.0 compatibility issue
  manager/controllers/default/resource/update.class.php
Labels: area-core, pr-state/review-needed

#14346 Add input prompt per setting to script
  .travis.yml
  _build/test/generateConfigs.sh
Labels: area-setup, pr-state/review-needed

#14681 Add back support for deprecated actions
  core/src/Revolution/Processors/System/ConfigJs.php
Labels: area-core, pr-state/review-needed

#14676 Fix an issue when process/action values are CamelCased
  manager/assets/modext/core/modx.component.js
Labels: pr-state/review-needed

#14593 Check if modx-content is defined before calling doLayout
  manager/assets/modext/widgets/core/modx.grid.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14592 Minor fixes for installer screens
  setup/templates/language.tpl
  setup/templates/options.tpl
  setup/templates/welcome.tpl
Labels: area-setup, pr-state/ready-for-merging

#14573 Fix set label or value of weblink/symlink field with Form Customization
  core/model/schema/modx.action.fields.schema.xml
Labels: pr-state/ready-for-merging

#14690 Add missing alias_visible field definition to model schemas
  core/model/modx/mysql/modresource.map.inc.php
  core/model/modx/sqlsrv/modresource.map.inc.php
  core/model/schema/modx.mysql.schema.xml
  core/model/schema/modx.sqlsrv.schema.xml
Labels: area-core, bug

#14445 SECURITY.md
  SECURITY.md
Labels: area-security, pr-state/review-needed

#14701 Escape instances of new MySQL reserved word rank
  core/model/modx/moddashboard.class.php
  core/model/modx/modformcustomizationset.class.php
  core/model/modx/processors/element/propertyset/getnodes.class.php
  core/model/modx/processors/element/template/duplicate.class.php
  core/model/modx/processors/resource/sort.class.php
  manager/controllers/default/resource/resource.class.php
Labels: area-core, bug, pr-state/ready-for-merging, priority-1-urgent
