Repository modxcms/revolution, pull requests merged in 2019-11, with the labels that each got.

#14797 Add more aliases
  core/include/deprecated.php
Labels: 3.x refactor, pr-state/ready-for-merging

#14808 Add permissions to the languages list array for Language Toggle
  core/src/Revolution/modMenu.php
Labels: area-core, bug, pr-state/ready-for-merging

#14807 Fix RecentlyEditedResources dashboard widget
  core/src/Revolution/Processors/Security/User/GetRecentlyEditedResources.php
Labels: area-core, bug, pr-state/review-needed

#14812 Update node-sass to a version that supports macOS Catalina
  _build/templates/default/package-lock.json
  _build/templates/default/package.json
Labels: pr-state/ready-for-merging

#14809 Check if component is rendered before using it's dom
  manager/assets/modext/widgets/security/modx.panel.groups.roles.js
Labels: bug, pr-state/ready-for-merging

#14801 Fixing limit for context settings
  core/model/modx/mysql/modcontextsetting.class.php
Labels: area-core, pr-state/ready-for-merging

#14819 Fixing limit for context settings
  core/src/Revolution/mysql/modContextSetting.php
Labels: area-core, pr-state/review-needed

#14827 Port modPackageBuilder, modTransportManager and modTransportVehicle
  core/src/Revolution/Transport/modPackageBuilder.php
  core/src/Revolution/Transport/modTransportManager.php
  core/src/Revolution/Transport/modTransportVehicle.php
Labels: 3.x refactor

#14839 Set autocomplete to off on username in user edit form (for 3.x)
  manager/assets/modext/widgets/security/modx.panel.user.js
Labels: area-ux/ui, pr-state/review-needed

#14836 Change the value of default_media_source_type system setting
  _build/data/transport.core.system_settings.php
  setup/includes/upgrades/common/3.0.0-update-default-media-source-setting.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: 3.x refactor, pr-state/review-needed

#14835 Implement setVisibility handler in modx-browser
  manager/assets/modext/widgets/media/modx.browser.js
Labels: area-ux/ui, pr-state/review-needed

#14834 Decode relativeURL
  manager/assets/modext/widgets/media/modx.browser.js
Labels: area-ux/ui, pr-state/review-needed

#14833 Fix displaying events in plugin panel
  core/src/Revolution/mysql/modEvent.php
Labels: bug, pr-state/ready-for-merging

#14826 Modify core class references in modContextSettings
  setup/includes/upgrades/common/3.0.0-update-legacy-class-references.php
Labels: 3.x refactor, bug, pr-state/review-needed, priority-1-urgent

#14838 Set autocomplete to off on username in user edit form
  manager/assets/modext/widgets/security/modx.panel.user.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14846 Fix missing use statement in update xtype system settings upgrade script
  setup/includes/upgrades/common/3.0.0-update-xtypes-system-settings.php
Labels: 3.x refactor, area-setup, pr-state/ready-for-merging

#14852 Changed "Top Menu" to "Main Menu"
  core/lexicon/en/action.inc.php
  core/lexicon/en/menu.inc.php
  core/lexicon/en/permissions.inc.php
  core/lexicon/en/setting.inc.php
  core/lexicon/en/topmenu.inc.php
Labels: pr-state/ready-for-merging

#14847 delete copies of the lexicon
  core/lexicon/en/setting.inc.php
Labels: area-i18n/l10n, pr-state/ready-for-merging

#14832 Changed resource styles in the tree
  _build/templates/default/sass/_colors-and-vars.scss
  _build/templates/default/sass/_tree.scss
  _build/templates/default/sass/index.scss
Labels: area-ux/ui, pr-state/review-needed

#14830 Added element name to browser title
  manager/controllers/default/security/forms/profile/update.class.php
  manager/controllers/default/source/update.class.php
  manager/controllers/default/system/dashboards/update.class.php
  manager/controllers/default/system/dashboards/widget/create.class.php
  manager/controllers/default/system/dashboards/widget/update.class.php
Labels: area-ux/ui, pr-state/ready-for-merging

#14786 Fixed display of icons in the tree
  _build/templates/default/sass/_tree.scss
Labels: area-ux/ui, pr-state/review-needed

#14856 Merge various system setting migration scripts into a single one
  setup/includes/upgrades/common/3.0.0-cleanup-authentication-security-system-settings.php
  setup/includes/upgrades/common/3.0.0-cleanup-lexicon-language-system-settings.php
  setup/includes/upgrades/common/3.0.0-cleanup-richtext-editor-system-settings.php
  setup/includes/upgrades/common/3.0.0-cleanup-system-settings.php
  setup/includes/upgrades/common/3.0.0-remove-tv-eval-system-setting.php
  setup/includes/upgrades/common/3.0.0-remove-upload-flash-system-setting.php
Labels: pr-state/ready-for-merging
