Repository modxcms/revolution, pull requests merged in 2019-10, with the labels that each got.

#14772 Fix rename files functionality in media browser
  manager/assets/modext/widgets/core/tree/modx.tree.js
Labels: area-ux/ui, pr-state/review-needed

#14752 Fixed browser styles
  _build/templates/default/sass/_browser.scss
Labels: area-ux/ui, pr-state/review-needed

#14783 Returned #modx-leftbar-trigger for mobile screens
  _build/templates/default/sass/_navbar.scss
Labels: pr-state/ready-for-merging

#14790 Only show the "frame" animation when dragging over visibible elements
  manager/assets/modext/widgets/modx.treedrop.js
Labels: area-ux/ui, pr-state/ready-for-merging

#14778 Fixed triangle submenu styles
  _build/templates/default/sass/_navbar.scss
Labels: pr-state/ready-for-merging

#14804 Use the fully qualified class names when possible
  _build/test/MODxTestCase.php
  _build/test/Tests/Model/Element/modElementTest.php
  _build/test/Tests/Model/Element/modPluginTest.php
  _build/test/Tests/Model/Element/modTagTest.php
  _build/test/Tests/Model/Hashing/modNativeHashTest.php
  _build/test/Tests/Model/Lexicon/modLexiconTest.php
  _build/test/Tests/Model/Registry/modFileRegisterTest.php
  _build/test/Tests/Model/Registry/modRegisterTest.php
  _build/test/Tests/Model/Registry/modRegistryTest.php
  _build/test/Tests/Model/Request/modRequestTest.php
  _build/test/Tests/Model/Security/modUserTest.php
  _build/test/Tests/Model/modParserTest.php
  core/src/Revolution/Filters/modOutputFilter.php
  core/src/Revolution/Processors/Context/Create.php
  core/src/Revolution/Processors/Context/UpdateFromGrid.php
  core/src/Revolution/Processors/Security/Access/Policy/Template/GetList.php
  core/src/Revolution/Processors/Security/User/Validation.php
  core/src/Revolution/Transport/modTransportPackage.php
  core/src/Revolution/modAccessPolicy.php
  core/src/Revolution/modCacheManager.php
  core/src/Revolution/modDashboardSnippetWidget.php
  core/src/Revolution/modElement.php
  core/src/Revolution/modExtensionPackage.php
  core/src/Revolution/modFormCustomizationSet.php
  core/src/Revolution/modParser.php
  core/src/Revolution/modRequest.php
  core/src/Revolution/modTag.php
  core/src/Revolution/modTemplate.php
  core/src/Revolution/modTemplateVar.php
  core/src/Revolution/modUser.php
  core/src/Revolution/modX.php
  core/src/Revolution/mysql/modEvent.php
  manager/controllers/default/context/update.class.php
  manager/controllers/default/context/view.class.php
  manager/controllers/default/resource/update.class.php
  manager/controllers/default/security/access/policy/template/update.class.php
  manager/controllers/default/security/access/policy/update.class.php
  manager/controllers/default/security/login.class.php
  manager/controllers/default/security/user/update.class.php
  setup/includes/modinstallversion.class.php
  setup/includes/upgrades/common/3.0.0-update-xtypes-system-settings.php
Labels: 3.x refactor

#14789 Update node-sass to a version that supports macOS Catalina
  _build/templates/default/package-lock.json
  _build/templates/default/package.json
Labels: pr-state/ready-for-merging
