Repository modxcms/revolution, pull requests merged in 2019-09, with the labels that each got.

#14545 Move "Deleted" checkbox from the resource settings to the main tab
  manager/assets/modext/widgets/resource/modx.panel.resource.js
Labels: area-ux/ui, pr-state/review-needed

#14464 Fix icon layout in action buttons
  _build/templates/default/sass/index.scss
Labels: area-ux/ui, pr-state/review-needed

#14709 Add missing changes from passwordless login
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  manager/controllers/default/security/login.class.php
  manager/templates/default/security/login.tpl
Labels: pr-state/review-needed, priority-2-high

#14710 Fix permission check causing fatal error on dashboard [#14707]
  manager/controllers/default/dashboard/widget.grid-online.php
  manager/controllers/default/dashboard/widget.grid-rer.php
  manager/templates/default/dashboard/onlineusers.tpl
  manager/templates/default/dashboard/recentlyeditedresources.tpl
Labels: pr-state/review-needed, priority-2-high

#14706 Fix several access-related processors (fixes #14696)
  core/src/Revolution/Processors/Security/Access/Policy/GetList.php
  core/src/Revolution/Processors/Security/Access/Policy/Template/GetList.php
  core/src/Revolution/Processors/Security/Role/GetAuthorityList.php
Labels: pr-state/review-needed

#14715 Call the right manager controller when saving a Template Variable
  manager/assets/modext/sections/element/tv/create.js
  manager/assets/modext/sections/element/tv/update.js
Labels: 3.x refactor, pr-state/review-needed

#14705 Escape usage of reserved name rank in sortby and groupby statements
  core/src/Revolution/Processors/Element/PropertySet/GetNodes.php
  core/src/Revolution/Processors/Element/Template/Duplicate.php
  core/src/Revolution/Processors/Resource/Sort.php
  core/src/Revolution/modDashboard.php
  core/src/Revolution/modFormCustomizationSet.php
  manager/controllers/default/resource/resource.class.php
Labels: pr-state/review-needed

#14386 Fix the bug with copying TVs when caption is empty
  core/model/modx/processors/element/tv/duplicate.class.php
Labels: area-core, pr-state/ready-for-merging

#14721 Use fully qualified class names for modTemplate
  _build/test/Tests/Model/Element/modTemplateTest.php
  core/src/Revolution/modTemplate.php
  core/src/Revolution/modTemplateVar.php
Labels: 3.x refactor, pr-state/ready-for-merging

#14722 Use fully qualified class names for modCategory
  core/src/Revolution/Processors/Element/GetNodes.php
  core/src/Revolution/Processors/Element/PropertySet/GetNodes.php
  core/src/Revolution/Processors/Element/Sort.php
  core/src/Revolution/modFormCustomizationSet.php
Labels: 3.x refactor, pr-state/ready-for-merging

#14682 Create the RSS cache directory if it doesn't exist
  core/src/Revolution/Processors/System/Dashboard/Widget/Feed.php
Labels: 3.x refactor, pr-state/ready-for-merging

#14728 Correct deprecation warning in modX::loadClass
  core/src/Revolution/modX.php
Labels: pr-state/review-needed

#14726 Made resource settings and quick resource window in one format
  manager/assets/modext/widgets/resource/modx.panel.resource.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
Labels: pr-state/review-needed

#14729 Fix listing categories and elements in nested categories
  core/src/Revolution/Processors/Element/GetNodes.php
Labels: pr-state/review-needed, priority-2-high

#14708 Show installation errors in a red block (Fixes #14654)
  _build/templates/default/sass/installer.scss
  setup/includes/test/modinstalltest.class.php
Labels: pr-state/review-needed

#14704 Make \modX and other class_aliases for backwards compatibility available in all requests
  _build/build.xml
  composer.json
  core/include/deprecated.php
  core/model/modx/modx.class.php
  core/src/Revolution/modX.php
  core/xpdo/xPDO.php
  core/xpdo/xPDOCacheManager.php
  core/xpdo/xPDOCriteria.php
  core/xpdo/xPDOFileCache.php
  core/xpdo/xPDOObject.php
  core/xpdo/xPDOQuery.php
  core/xpdo/xPDOSimpleObject.php
  core/xpdo/xPDOTransport.php
  core/xpdo/xpdo.class.php
Labels: pr-state/review-needed, priority-2-high

#14689 Generate sortable tag signature with serialized array values
  core/src/Revolution/modElement.php
Labels: area-core

#14731 Corrected profile layout
  manager/assets/modext/sections/security/profile/update.js
Labels: pr-state/review-needed

#14739 Prevent users without edit_locked permission from editing locked elements
  core/model/modx/processors/element/update.class.php
  manager/controllers/default/element/chunk/update.class.php
Labels: pr-state/review-needed

#14756 Load the setup assets when MODX is inside a subdirectory
  setup/templates/header.tpl
Labels: area-setup, pr-state/review-needed

#14664 Fixed transparency in .png for TV
  core/model/phpthumb/phpthumb.class.php
  manager/templates/default/element/tv/renders/input/image.tpl
Labels: pr-state/ready-for-merging

#14658 Resolved required 0 integer values being incorrectly marked as undefined
  core/model/modx/rest/modrestcontroller.class.php
Labels: pr-state/ready-for-merging
