Repository modxcms/revolution, pull requests merged in 2020-01, with the labels that each got.

#14923 Fix pass-by-reference and incompatible declarations for controllers and processors
  core/src/Revolution/Processors/Resource/Create.php
  core/src/Revolution/Processors/Resource/Update.php
  core/src/Revolution/Processors/Security/User/Create.php
  core/src/Revolution/Processors/Security/User/Update.php
  core/src/Revolution/Processors/System/DatabaseTable/GetList.php
  core/src/Revolution/Processors/System/DatabaseTable/Optimize.php
  core/src/Revolution/Processors/System/DatabaseTable/OptimizeDatabase.php
  core/src/Revolution/Processors/System/DatabaseTable/Truncate.php
  core/src/Revolution/modManagerController.php
  manager/controllers/default/resource/resource.class.php
Labels: pr-state/ready-for-merging

#14924 Fix category actions missing from context menu, and inability to drop elements on categories
  manager/assets/modext/widgets/element/modx.tree.element.js
Labels: pr-state/review-needed

#14933 Removed unnecessary fully qualified class names
  core/src/Revolution/Sources/modMediaSource.php
  core/src/Revolution/modActionDom.php
  setup/includes/request/modinstallclirequest.class.php
Labels: area-core, enhancement, pr-state/review-needed

#14936 Updated links to prevent redirects and broken pages
  README.md
  composer.json
  core/lexicon/en/configcheck.inc.php
  core/lexicon/en/formcustomization.inc.php
  core/lexicon/en/login.inc.php
  manager/controllers/default/dashboard/widget.updates.php
  setup/lang/en/default.inc.php
  setup/templates/base_resource.tpl
  setup/templates/base_template.tpl
  setup/templates/findcore.php
  setup/templates/index.tpl
Labels: pr-state/review-needed

#14937 Disable actionsColumn for FC grids
  manager/assets/modext/widgets/fc/modx.panel.fcset.js
Labels: area-ux/ui

#14946 Apply `MODx.util.safeHtml` to make the feed dashboards a bit safer
  manager/assets/modext/widgets/modx.panel.welcome.js
Labels: area-security, pr-state/review-needed

#14938 Disable actionsColumn for ACL grids
  manager/assets/modext/widgets/security/modx.grid.role.js
  manager/assets/modext/widgets/security/modx.panel.access.policy.js
Labels: area-ux/ui, pr-state/review-needed

#14472 Check extracted files for allowed extensions by option
  core/model/modx/modfilehandler.class.php
Labels: area-security, bug

#14960 Fix upgrade error "Error updating table for class MODX\Revolution\modUser"
  setup/includes/upgrades/common/3.0.0-update-legacy-class-references.php
Labels: 3.x refactor, area-setup, pr-state/review-needed

#14964 Add additional services and common class references to the class_alias list
  core/include/deprecated.php
Labels: cla-signed, pr-state/review-needed, priority-2-high

#14947 Update broken recycle bin getlist
  core/src/Revolution/Processors/Resource/Trash/GetList.php
Labels: area-core, cla-signed, pr-state/awaiting-an-author
