Repository modxcms/revolution, pull requests merged in 2020-06, with the labels that each got.

#15016 Show "Input Option Values" with labels only on TV where it needed
  manager/assets/modext/widgets/element/modx.panel.tv.js
  manager/templates/default/element/tv/renders/inputproperties/autotag.tpl
  manager/templates/default/element/tv/renders/inputproperties/checkbox.tpl
  manager/templates/default/element/tv/renders/inputproperties/date.tpl
  manager/templates/default/element/tv/renders/inputproperties/email.tpl
  manager/templates/default/element/tv/renders/inputproperties/file.tpl
  manager/templates/default/element/tv/renders/inputproperties/image.tpl
  manager/templates/default/element/tv/renders/inputproperties/list-multiple-legacy.tpl
  manager/templates/default/element/tv/renders/inputproperties/listbox-multiple.tpl
  manager/templates/default/element/tv/renders/inputproperties/listbox.tpl
  manager/templates/default/element/tv/renders/inputproperties/number.tpl
  manager/templates/default/element/tv/renders/inputproperties/radio.tpl
  manager/templates/default/element/tv/renders/inputproperties/resourcelist.tpl
  manager/templates/default/element/tv/renders/inputproperties/tag.tpl
  manager/templates/default/element/tv/renders/inputproperties/text.tpl
  manager/templates/default/element/tv/renders/inputproperties/textarea.tpl
Labels: cla-signed, pr-state/review-needed

#15042 Corrected TV form with the Number type
  manager/templates/default/element/tv/renders/inputproperties/number.tpl
Labels: cla-signed, pr-state/review-needed

#15059 Merge option for setProperties() methods that don't have a merge option
  core/src/Revolution/Processors/Processor.php
  core/src/Revolution/modManagerController.php
Labels: area-core, cla-signed, pr-state/ready-for-merging, pr-state/review-needed

#15066 Collapse/expand all child nodes in elements tree
  manager/assets/modext/widgets/element/modx.tree.element.js
Labels: cla-signed, pr-state/ready-for-merging, pr-state/review-needed

#15072 Corrected width for allowBlank in TV form
  manager/templates/default/element/tv/renders/inputproperties/autotag.tpl
  manager/templates/default/element/tv/renders/inputproperties/tag.tpl
  manager/templates/default/element/tv/renders/inputproperties/textarea.tpl
Labels: area-ux/ui, cla-signed, pr-state/ready-for-merging

#15073 Added allowBlank for TV with URL type
  manager/templates/default/element/tv/renders/input/url.tpl
  manager/templates/default/element/tv/renders/inputproperties/url.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15074 Added allowBlank for TV with RichText type
  core/src/Revolution/Processors/Element/TemplateVar/Renders/mgr/inputproperties/richtext.php
  manager/templates/default/element/tv/renders/input/richtext.tpl
  manager/templates/default/element/tv/renders/inputproperties/richtext.tpl
Labels: area-ux/ui, cla-signed, pr-state/ready-for-merging

#15075 Added allowBlank for TV with Image and File type
  manager/assets/modext/core/modx.js
  manager/assets/modext/widgets/element/modx.panel.tv.renders.js
  manager/templates/default/element/tv/renders/input/file.tpl
  manager/templates/default/element/tv/renders/input/image.tpl
  manager/templates/default/element/tv/renders/inputproperties/file.tpl
  manager/templates/default/element/tv/renders/inputproperties/image.tpl
Labels: area-ux/ui, cla-signed, pr-state/ready-for-merging

#15077 Fix conditions with request action [JS]
  manager/assets/modext/widgets/element/modx.panel.chunk.js
  manager/assets/modext/widgets/element/modx.panel.plugin.js
  manager/assets/modext/widgets/element/modx.panel.snippet.js
  manager/assets/modext/widgets/element/modx.panel.template.js
  manager/assets/modext/widgets/element/modx.panel.tv.js
  manager/assets/modext/widgets/resource/modx.panel.resource.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
  manager/assets/modext/widgets/system/modx.tree.directory.js
Labels: cla-signed, pr-state/ready-for-merging

#15107 Corrected form ID for media source panel
  manager/assets/modext/widgets/source/modx.panel.source.js
Labels: cla-signed, pr-state/ready-for-merging

#15108 Changed header to a more specific in user grid
  manager/assets/modext/widgets/security/modx.grid.user.js
Labels: cla-signed, pr-state/ready-for-merging

#15110 Set 'publishedon' to get() for 'publishedon_adjusted'
  core/src/Revolution/Processors/Resource/Data.php
Labels: cla-signed, pr-state/ready-for-merging

#15121 Corrected form ID for fcp panel
  manager/assets/modext/widgets/fc/modx.panel.fcprofile.js
Labels: cla-signed, pr-state/ready-for-merging

#15106 Fixed allowBlank for TV with URL, RichText, Image & File types
  core/docs/changelog.txt
  core/model/modx/processors/element/tv/renders/mgr/inputproperties/richtext.php
  manager/assets/modext/widgets/element/modx.panel.tv.renders.js
  manager/templates/default/element/tv/renders/input/file.tpl
  manager/templates/default/element/tv/renders/input/image.tpl
  manager/templates/default/element/tv/renders/input/richtext.tpl
  manager/templates/default/element/tv/renders/input/url.tpl
  manager/templates/default/element/tv/renders/inputproperties/image.tpl
  manager/templates/default/element/tv/renders/inputproperties/richtext.tpl
  manager/templates/default/element/tv/renders/inputproperties/url.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15124 Changing old documentation links to current ones
  core/lexicon/en/configcheck.inc.php
  setup/templates/base_resource.tpl
  setup/templates/base_template.tpl
Labels: cla-signed

#15139 Added a section for the issue / PR
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cla-signed

#15125 Corrected tabs ID for system settings panel
  manager/assets/modext/widgets/system/modx.panel.system.settings.js
Labels: cla-signed, pr-state/ready-for-merging
