Repository modxcms/revolution, pull requests merged in 2020-02, with the labels that each got.

#14303 Log deprecated modAction for the current installed package only during package install/uninstall
  core/model/modx/modmenu.class.php
  core/model/modx/processors/workspace/packages/install.class.php
  core/model/modx/processors/workspace/packages/uninstall.class.php
Labels: area-core, bug, pr-state/review-needed

#14993 Fix loading static element content
  _build/test/Tests/Model/Element/modStaticElementTest.php
  core/src/Revolution/modElement.php
Labels: cla-signed, pr-state/review-needed, priority-1-urgent

#14983 Added breadcrumbs to FC and ACL sections
  manager/assets/modext/widgets/fc/modx.panel.fcprofile.js
  manager/assets/modext/widgets/fc/modx.panel.fcset.js
  manager/assets/modext/widgets/security/modx.panel.access.policy.js
  manager/assets/modext/widgets/security/modx.panel.access.policy.template.js
  manager/assets/modext/widgets/security/modx.panel.user.group.js
  manager/assets/modext/widgets/security/modx.panel.user.js
  manager/assets/modext/widgets/source/modx.panel.source.js
  manager/assets/modext/widgets/system/modx.panel.context.js
  manager/assets/modext/widgets/system/modx.panel.dashboard.js
  manager/assets/modext/widgets/system/modx.panel.dashboard.widget.js
  manager/controllers/default/security/forms/set/update.class.php
Labels: cla-signed, pr-state/ready-for-merging

#14994 Fix package dependency constraints not working
  core/src/Revolution/Transport/modTransportPackage.php
Labels: cla-signed, pr-state/ready-for-merging

#14996 Show an error message too, if the core use an old autoloader.
  setup/processors/database/connection.php
Labels: cla-signed, pr-state/ready-for-merging

#14978 Improve some dialog stylings
  _build/templates/default/sass/_windows.scss
Labels: area-ux/ui, cla-signed, pr-state/review-needed

#14997 Fix drag and drop not working by removing the reference to MODx.action
  manager/assets/modext/widgets/resource/modx.tree.resource.js
  manager/assets/modext/widgets/system/modx.tree.directory.js
Labels: cla-signed, pr-state/review-needed

#14998 Add context key to reload URL when switching templates
  manager/assets/modext/widgets/resource/modx.panel.resource.js
Labels: cla-signed, pr-state/review-needed

#15011 Switched string literals to use single quotes so that it is compatibl…
  core/model/modx/transport/mysql/modtransportpackage.class.php
Labels: bug, cla-signed

#15023 Fix trash getlist processor for invalid parents
  core/model/modx/processors/resource/trash/getlist.class.php
Labels: area-core, bug, cla-signed, pr-state/review-needed
