Repository modxcms/revolution, pull requests merged in 2020-12, with the labels that each got.

#15158 Made quick search more convenient by adding system settings
  _build/data/transport.core.system_settings.php
  _build/templates/default/sass/_uberbar.scss
  core/docs/changelog.txt
  core/lexicon/en/setting.inc.php
  core/src/Revolution/Processors/Search/Search.php
  manager/assets/ext3/resources/charts.swf
  manager/assets/modext/widgets/core/tree/modx.tree.js
  manager/assets/modext/widgets/element/modx.tree.element.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: cla-signed, pr-state/ready-for-merging

#15159 Improve Navigation for Access Control Lists > User Groups & Users
  core/docs/changelog.txt
  manager/assets/modext/widgets/security/modx.panel.user.group.js
Labels: cla-signed, pr-state/ready-for-merging

#15179 Changed the lexicon to be more specific
  core/lexicon/en/default.inc.php
  manager/assets/modext/widgets/security/modx.grid.user.group.settings.js
  manager/assets/modext/widgets/security/modx.grid.user.settings.js
  manager/assets/modext/widgets/system/modx.grid.context.settings.js
Labels: cla-signed, pr-state/ready-for-merging

#15181 Remember filter properties of packages grid in browser url
  manager/assets/modext/workspace/package.containers.js
  manager/assets/modext/workspace/package.grid.js
Labels: cla-signed, pr-state/ready-for-merging

#15182 Added remembering filter properties of sources grid in browser url
  manager/assets/modext/widgets/source/modx.panel.sources.js
Labels: cla-signed, pr-state/ready-for-merging

#15183 Added remembering filter properties of contexts grid in browser url
  _build/templates/default/sass/_buttons.scss
  manager/assets/modext/widgets/system/modx.grid.context.js
Labels: cla-signed, pr-state/ready-for-merging

#15184 Added remembering filter properties of namespaces grid in browser url
  manager/assets/modext/workspace/namespace/modx.namespace.panel.js
Labels: cla-signed, pr-state/ready-for-merging

#15185 Added remembering filter properties of fcp grid in browser url
  manager/assets/modext/widgets/fc/modx.grid.fcprofile.js
Labels: cla-signed, pr-state/ready-for-merging

#15186 Added remembering filter properties of fcsets grid in browser url
  manager/assets/modext/widgets/fc/modx.grid.fcset.js
  manager/assets/modext/widgets/fc/modx.panel.fcprofile.js
Labels: cla-signed, pr-state/ready-for-merging

#15192 Changed the width of input fields for "Edit File" form
  manager/assets/modext/sections/system/file/edit.js
Labels: cla-signed, pr-state/ready-for-merging

#15193 Changed the width of fields for "Package" panel
  manager/assets/modext/workspace/package/package.panel.js
Labels: cla-signed, pr-state/ready-for-merging

#15196 Changed "Template Variable" to "TV" in lexicons
  core/lexicon/en/category.inc.php
  core/lexicon/en/default.inc.php
  core/lexicon/en/formcustomization.inc.php
  core/lexicon/en/permissions.inc.php
  core/lexicon/en/setting.inc.php
  core/lexicon/en/template.inc.php
  core/lexicon/en/tv.inc.php
Labels: cla-signed, pr-state/ready-for-merging

#15197 Unify manager actions to lowercase
  manager/assets/modext/widgets/fc/modx.grid.fcprofile.js
  manager/assets/modext/widgets/fc/modx.grid.fcset.js
  manager/assets/modext/widgets/resource/modx.panel.resource.data.js
  manager/assets/modext/widgets/resource/modx.panel.resource.js
Labels: cla-signed, pr-state/ready-for-merging

#15202 Added an icon for "Resource Groups", "User Groups" & "Property Sets" sections tree
  manager/assets/modext/widgets/element/modx.panel.property.set.js
  manager/assets/modext/widgets/security/modx.tree.resource.group.js
  manager/assets/modext/widgets/security/modx.tree.user.group.js
Labels: cla-signed, pr-state/ready-for-merging

#15212 Fixed options for TV output with date type
  manager/templates/default/element/tv/renders/properties/date.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15217 Changed id for options for TV output with html-tag type
  core/lexicon/en/tv_widget.inc.php
  manager/templates/default/element/tv/renders/properties/htmltag.tpl
  setup/includes/upgrades/common/3.0.0-update-tvs-output-params.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: cla-signed, pr-state/ready-for-merging

#15230 Fixed work with menu items in the main menu
  manager/assets/modext/widgets/system/modx.tree.menu.js
Labels: cla-signed, pr-state/ready-for-merging

#15241 Added class with padding for package update window
  manager/assets/modext/workspace/package.grid.js
Labels: cla-signed, pr-state/ready-for-merging

#15266 Fix JavaScript error when create a new folder in the root
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/system/modx.tree.directory.js
Labels: cla-signed, pr-state/ready-for-merging

#15275 Normalize error message
  core/lexicon/en/tv.inc.php
Labels: cla-signed, pr-state/ready-for-merging

#15321 Fixed display of the pagination toolbar
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.combo.js
Labels: cla-signed, pr-state/ready-for-merging

#15336 Revise cache clearing lexicons
  core/lexicon/en/default.inc.php
Labels: area-i18n/l10n, cla-signed, pr-state/ready-for-merging

#15351 Wrong term documents
  core/lexicon/en/tv.inc.php
Labels: cla-signed
