Repository modxcms/revolution, pull requests merged in 2020-08, with the labels that each got.

#15044 Corrected the TV form with the Listbox (Multi-Select) type
  manager/templates/default/element/tv/renders/input/listbox-multiple.tpl
  manager/templates/default/element/tv/renders/inputproperties/listbox-multiple.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15178 Update htaccess delete rules for win xp and IE
  ht.access
Labels: cla-signed, pr-state/ready-for-merging

#14999 Setup improvements
  setup/assets/js/sections/welcome.js
  setup/controllers/language.php
  setup/includes/request/modinstallrequest.class.php
  setup/index.php
  setup/lang/en/default.inc.php
  setup/provisioner/bootstrap.php
  setup/provisioner/requirements.php
  setup/templates/header.tpl
  setup/templates/requirements.php
  setup/templates/welcome.tpl
Labels: cla-signed, pr-state/review-needed

#15109 Corrected output of resource data in "Overview" form
  manager/assets/modext/widgets/resource/modx.panel.resource.data.js
Labels: cla-signed, pr-state/review-needed

#15112 Recreate form customization menu entry
  setup/includes/upgrades/common/3.0.0-update-menu-entries.php
Labels: cla-signed

#15135 [3x] Enable GitHub Dependabot version updates for dependencies
  .github/dependabot.yml
Labels: cla-signed, pr-state/review-needed

#15199 Fix PHP error with absent array index
  core/model/modx/processors/element/getnodes.class.php
Labels: cla-signed

#15104 [3.x] Add node@12 as dev dependencies fixing node-sass errors
  _build/templates/default/package-lock.json
  _build/templates/default/package.json
Labels: cla-signed, pr-state/ready-for-merging

#15205 Fix of checking existence of <?php tag
  manager/controllers/default/element/plugin/update.class.php
  manager/controllers/default/element/snippet/update.class.php
Labels: cla-signed

#15211 Fix of checking existence of <?php tag
  manager/controllers/default/element/plugin/update.class.php
  manager/controllers/default/element/snippet/update.class.php
Labels: cla-signed

#15160 Register woff2 format in system settings
  _build/data/transport.core.system_settings.php
  setup/includes/upgrades/common/2.8.0-update-upload_files-woff2.php
  setup/includes/upgrades/mysql/2.8.0-pl.php
  setup/includes/upgrades/sqlsrv/2.8.0-pl.php
Labels: cla-signed, pr-state/ready-for-merging

#15210 Register woff2 format in system settings
  _build/data/transport.core.system_settings.php
  setup/includes/upgrades/common/3.0.0-update-upload_files-woff2.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: cla-signed

#15215 Fix login screen php notice
  manager/templates/default/security/login.tpl
Labels: cla-signed

#15214 Fix PHP error with absent array index
  core/src/Revolution/Processors/Element/GetNodes.php
Labels: cla-signed

#15213 Fixed PHP notice "Undefined index" for resources without a template
  manager/controllers/default/resource/resource.class.php
Labels: cla-signed
