Repository modxcms/revolution, pull requests merged in 2020-04, with the labels that each got.

#15045 Corrected TV form with the Text type
  manager/templates/default/element/tv/renders/inputproperties/text.tpl
Labels: area-ux/ui, cla-signed, pr-state/ready-for-merging

#15064 Corrected TV form with the Email type
  manager/templates/default/element/tv/renders/inputproperties/email.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15065 Corrected TV form with the Legacy multiple list type
  core/lexicon/en/tv_widget.inc.php
  manager/templates/default/element/tv/renders/input/list-multiple-legacy.tpl
  manager/templates/default/element/tv/renders/inputproperties/list-multiple-legacy.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15063 Corrected TV form with the Radio and Checkbox type
  manager/templates/default/element/tv/renders/inputproperties/checkbox.tpl
  manager/templates/default/element/tv/renders/inputproperties/radio.tpl
Labels: cla-signed

#14979 Lexicon check for the core
  _build/lexicon/.gitignore
  _build/lexicon/checklexicon.php
Labels: area-i18n/l10n, cla-signed, enhancement, pr-state/review-needed

#15009 Corrected TV form with the Date type
  manager/templates/default/element/tv/renders/inputproperties/date.tpl
Labels: cla-signed, pr-state/review-needed

#15043 Corrected TV form with the ResourceList type
  core/lexicon/en/tv_widget.inc.php
  core/src/Revolution/Processors/Element/TemplateVar/Renders/mgr/input/resourcelist.class.php
  manager/templates/default/element/tv/renders/input/resourcelist.tpl
  manager/templates/default/element/tv/renders/inputproperties/resourcelist.tpl
Labels: cla-signed, needs documentation
