Repository modxcms/revolution, pull requests merged in 2021-03, with the labels that each got.

#15421 PHP8 compatibility for 3.x
  .github/workflows/ci.yml
  .gitignore
  _build/build.properties.sample.php
  _build/test/MODxControllerTestCase.php
  _build/test/MODxTestCase.php
  _build/test/Tests/Cases/Modx/ReplaceReservedTest.php
  _build/test/Tests/Cases/Request/MakeUrlTest.php
  _build/test/Tests/Controllers/Context/ContextUpdateControllerTest.php
  _build/test/Tests/Controllers/LoadControllerTest.php
  _build/test/Tests/Controllers/Resources/ResourceCreateControllerTest.php
  _build/test/Tests/Controllers/Resources/StaticResource/StaticResourceCreateControllerTest.php
  _build/test/Tests/Controllers/Resources/SymLink/SymLinkCreateControllerTest.php
  _build/test/Tests/Controllers/Resources/WebLink/WebLinkCreateControllerTest.php
  _build/test/Tests/Controllers/WelcomeControllerTest.php
  _build/test/Tests/Model/Dashboard/modDashboardTest.php
  _build/test/Tests/Model/Dashboard/modDashboardWidgetTest.php
  _build/test/Tests/Model/Element/modChunkTest.php
  _build/test/Tests/Model/Element/modPluginTest.php
  _build/test/Tests/Model/Element/modSnippetTest.php
  _build/test/Tests/Model/Element/modStaticElementTest.php
  _build/test/Tests/Model/Element/modTagTest.php
  _build/test/Tests/Model/Element/modTemplateTest.php
  _build/test/Tests/Model/Element/modTemplateVarTest.php
  _build/test/Tests/Model/Error/modErrorTest.php
  _build/test/Tests/Model/Filters/modOutputFilterTest.php
  _build/test/Tests/Model/FormCustomization/modActionDomTest.php
  _build/test/Tests/Model/Lexicon/modLexiconTest.php
  _build/test/Tests/Model/Mail/modMailTest.php
  _build/test/Tests/Model/Registry/modFileRegisterTest.php
  _build/test/Tests/Model/Registry/modRegisterTest.php
  _build/test/Tests/Model/Registry/modRegistryTest.php
  _build/test/Tests/Model/Request/modRequestTest.php
  _build/test/Tests/Model/Security/modUserTest.php
  _build/test/Tests/Model/Sources/modFileMediaSourceTest.php
  _build/test/Tests/Model/Sources/modMediaSourceTest.php
  _build/test/Tests/Model/modParserTest.php
  _build/test/Tests/Model/modXTest.php
  _build/test/Tests/Processors/Browser/DirectoryTest.php
  _build/test/Tests/Processors/Context/ContextSettingTest.php
  _build/test/Tests/Processors/Context/ContextTest.php
  _build/test/Tests/Processors/Element/CategoryTest.php
  _build/test/Tests/Processors/Element/ChunkTest.php
  _build/test/Tests/Processors/Element/PluginTest.php
  _build/test/Tests/Processors/Element/PropertySetTest.php
  _build/test/Tests/Processors/Element/SnippetTest.php
  _build/test/Tests/Processors/Element/TemplateTest.php
  _build/test/Tests/Processors/Element/TemplateVarTest.php
  _build/test/Tests/Processors/Resource/ResourceCreateTest.php
  _build/test/Tests/Transport/TransportCoreTest.php
  _build/test/Tests/modXSetupTest.php
  _build/test/Tests/modXTeardownTest.php
  _build/test/phpunit.xml
  _build/test/properties.sample.inc.php
  composer.json
  core/src/Revolution/modTemplateVar.php
  core/src/Revolution/modX.php
  setup/includes/new.install.php
Labels: cla-signed, pr-state/review-needed, priority-2-high

#15399 Fix setup option upgrade existing install
  setup/includes/modinstallsettings.class.php
Labels: cla-signed, pr-state/review-needed

#15264 Add check that the file exists when uploading it
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/src/Revolution/Sources/modMediaSource.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/util/multiuploaddialog.js
Labels: cla-signed, pr-state/review-needed

#15376 Update modUser.php
  core/src/Revolution/modUser.php
Labels: cla-signed, pr-state/review-needed

#15377 Update modLexicon.php
  core/src/Revolution/modLexicon.php
Labels: cla-signed, pr-state/review-needed

#15388 Menu improvements
  core/src/Revolution/Processors/System/Menu/GetNodes.php
  manager/assets/modext/widgets/system/modx.tree.menu.js
Labels: cla-signed, pr-state/review-needed

#15390 Adjust user customized dashboards
  core/src/Revolution/Processors/System/Dashboard/Update.php
Labels: cla-signed, pr-state/review-needed

#15436 Fixing an error when installing using composer
  _build/data/transport.core.system_settings.php
Labels: cla-signed, pr-state/review-needed

#15447 Fixed lexicon to correct one
  core/lexicon/en/default.inc.php
Labels: cla-signed, pr-state/ready-for-merging

#15443 Fixed incorrect hour checks for the greeting message.
  manager/controllers/default/security/login.class.php
Labels: cla-signed, pr-state/ready-for-merging

#15440 Fixed warnings about incorrect passed variables (#13943)
  core/src/Revolution/Sources/modMediaSource.php
Labels: cla-signed, pr-state/ready-for-merging

#15435 Fixed a notice about undefined index icon in the site manager (#15433).
  manager/controllers/default/header.php
Labels: cla-signed, pr-state/review-needed

#15427 Adjust getParents method to work with deleted resources
  core/docs/changelog.txt
  manager/controllers/default/resource/resource.class.php
Labels: area-core, bug, cla-signed

#15452 Disable actionsColumn for Dashboards grid in Widget section
  manager/assets/modext/widgets/system/modx.panel.dashboard.widget.js
Labels: cla-signed, pr-state/review-needed

#15475 Run manager style and scripts building via npm run.
  _build/templates/default/package.json
Labels: cla-signed, pr-state/ready-for-merging

#15411 Updating url in system setting base_help_url
  _build/data/transport.core.system_settings.php
  setup/includes/upgrades/common/3.0.0-update-base_help_url.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: cla-signed, pr-state/ready-for-merging

#15422 Remove http:// from empty weblink field on resource create form
  core/lexicon/en/resource.inc.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/resource/modx.panel.resource.weblink.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
Labels: cla-signed, pr-state/ready-for-merging

#15459 Fixed PHP notices on the resource form
  manager/templates/default/resource/create.tpl
  manager/templates/default/resource/staticresource/create.tpl
  manager/templates/default/resource/staticresource/update.tpl
  manager/templates/default/resource/symlink/create.tpl
  manager/templates/default/resource/symlink/update.tpl
  manager/templates/default/resource/update.tpl
  manager/templates/default/resource/weblink/create.tpl
  manager/templates/default/resource/weblink/update.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15463 Added display of the name of elements in delete messages
  core/lexicon/en/access.inc.php
  core/lexicon/en/file.inc.php
  core/lexicon/en/menu.inc.php
  core/lexicon/en/resource.inc.php
  core/lexicon/en/user.inc.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/sections/resource/update.js
  manager/assets/modext/widgets/media/modx.browser.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
  manager/assets/modext/widgets/security/modx.grid.user.group.js
  manager/assets/modext/widgets/security/modx.tree.resource.group.js
  manager/assets/modext/widgets/security/modx.tree.user.group.js
  manager/assets/modext/widgets/system/modx.tree.directory.js
  manager/assets/modext/widgets/system/modx.tree.menu.js
Labels: area-ux/ui, cla-signed, enhancement, pr-state/ready-for-merging

#15466 Fix logging Could not load package metadata for package modx.transport
  core/src/Revolution/Processors/Workspace/Packages/Get.php
  core/src/Revolution/Processors/Workspace/Packages/GetList.php
  core/src/Revolution/Processors/Workspace/Packages/Version/GetList.php
Labels: cla-signed

#15477 Import missing classes
  _build/test/Tests/Controllers/Resources/SymLink/SymLinkCreateControllerTest.php
  _build/test/Tests/Model/Request/modRequestTest.php
  core/src/Revolution/Processors/Security/Role/UpdateFromGrid.php
  core/src/Revolution/Processors/System/Log/GetList.php
  core/src/Revolution/Processors/System/Menu/Remove.php
  core/src/Revolution/modNamespace.php
  manager/controllers/default/element/chunk/create.class.php
  manager/controllers/default/element/plugin/create.class.php
  manager/controllers/default/element/plugin/update.class.php
  manager/controllers/default/element/snippet/create.class.php
  manager/controllers/default/element/snippet/update.class.php
  manager/controllers/default/element/template/create.class.php
  manager/controllers/default/element/template/update.class.php
  manager/controllers/default/element/tv/create.class.php
  manager/controllers/default/element/tv/update.class.php
  manager/controllers/default/resource/update.class.php
  manager/controllers/default/security/access/policy/template/update.class.php
  manager/controllers/default/security/access/policy/update.class.php
  manager/controllers/default/workspaces/index.class.php
  setup/includes/modinstallversion.class.php
  setup/includes/upgrade.install.php
  setup/includes/upgrades/common/3.0.0-update-upload_files-woff2.php
Labels: cla-signed, pr-state/ready-for-merging

#15485 Increased the width of the text (input) TV
  manager/templates/default/element/tv/renders/input/autotag.tpl
  manager/templates/default/element/tv/renders/input/email.tpl
  manager/templates/default/element/tv/renders/input/number.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15512 Incorrect regular expression for the downloaded file.
  core/src/Revolution/Processors/Browser/File/Download.php
Labels: cla-signed, pr-state/ready-for-merging

#15519 Replace 'modPlugin' with modPlugin::class in elementClassKey checks
  core/src/Revolution/Processors/Element/GetNodes.php
Labels: cla-signed, pr-state/ready-for-merging

#15520 Update editorconfig rules
  .editorconfig
Labels: cla-signed, pr-state/ready-for-merging

#15488 properties for @CHUNK and @SNIPPET binding
  core/src/Revolution/modTemplateVar.php
Labels: area-core, cla-signed, enhancement, needs documentation, pr-state/ready-for-merging

#15410 Updating url in system setting base_help_url
  _build/data/transport.core.system_settings.php
  setup/includes/upgrades/common/2.8.2-update-base_help_url.php
  setup/includes/upgrades/mysql/2.8.2-pl.php
  setup/includes/upgrades/sqlsrv/2.8.2-pl.php
Labels: cla-signed, pr-state/ready-for-merging

#15545 Adjust PR template to encourage using right format to connect issues
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla-signed, pr-state/ready-for-merging

#15548 Changing the naming of upgrades of scripts for updating system settings
  setup/includes/upgrades/common/3.0.0-update-sys-setting_base_help_url.php
  setup/includes/upgrades/common/3.0.0-update-sys-setting_default_media_source.php
  setup/includes/upgrades/common/3.0.0-update-sys-setting_upload_files-upload_images.php
  setup/includes/upgrades/common/3.0.0-update-sys-setting_upload_files-woff2.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: cla-signed

#15505 Fix bug with special chars in the directory or file names
  core/model/modx/processors/browser/directory/getfiles.class.php
  core/model/modx/processors/browser/directory/getlist.class.php
  core/model/modx/processors/browser/file/create.class.php
  core/model/modx/sources/modfilemediasource.class.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/media/modx.browser.js
Labels: cla-signed, pr-state/review-needed

#15536 Create a system setting mail_smtp_autotls
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/model/modx/mail/modmail.class.php
  core/model/modx/mail/modphpmailer.class.php
Labels: cla-signed, pr-state/port-to-3.x, pr-state/review-needed

#15549 Create a system setting mail_smtp_autotls
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/src/Revolution/Mail/modMail.php
  core/src/Revolution/Mail/modPHPMailer.php
Labels: cla-signed, needs documentation, pr-state/review-needed

#15424 Changed old class name to FCQN in the class_key for resources in the tree
  manager/assets/modext/core/modx.layout.js
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.searchbar.js
  manager/assets/modext/widgets/resource/modx.panel.resource.js
  manager/assets/modext/widgets/resource/modx.panel.resource.static.js
  manager/assets/modext/widgets/resource/modx.panel.resource.symlink.js
  manager/assets/modext/widgets/resource/modx.panel.resource.weblink.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
Labels: cla-signed, pr-state/ready-for-merging

#15552 Set controller property in controller's config
  core/src/Revolution/modManagerResponse.php
Labels: cla-signed, pr-state/ready-for-merging

#15547 Adds missing lexicon file_folder_err_update
  core/lexicon/en/file.inc.php
Labels: cla-signed, pr-state/ready-for-merging

#15456 Fixed PHP notices on the login page.
  manager/templates/default/security/login.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15484 Fix image rotation in media browser #modxbughunt
  core/src/Revolution/Sources/modMediaSource.php
Labels: cla-signed, pr-state/ready-for-merging

#15526 Improved check to see if the key "url" exists in media source $properties array. This fixes the preview thumbnail issue.
  core/src/Revolution/Sources/modMediaSource.php
Labels: cla-signed, pr-state/ready-for-merging

#15529 Adjust class names in principal_targets system setting
  _build/data/transport.core.system_settings.php
  core/src/Revolution/modPrincipal.php
  setup/includes/upgrades/common/3.0.0-update-principal_targets.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: cla-signed, pr-state/ready-for-merging

#14009 Translated descriptions for policies, policy templates and policy template groups
  _build/data/permissions/transport.policy.tpl.mediasource.php
  _build/data/transport.core.accesspolicies.php
  _build/data/transport.core.accesspolicytemplategroups.php
  _build/data/transport.core.accesspolicytemplates.php
  _build/resolvers/resolve.policies.php
  _build/resolvers/resolve.policytemplates.php
  core/lexicon/en/policy.inc.php
  core/src/Revolution/Processors/Model/GetListProcessor.php
  core/src/Revolution/Processors/Security/Access/Policy/GetList.php
  core/src/Revolution/Processors/Security/Access/Policy/Template/GetList.php
  core/src/Revolution/Processors/Security/Access/Policy/Template/Group/GetList.php
  core/src/Revolution/Processors/Security/Access/Policy/Template/UpdateFromGrid.php
  core/src/Revolution/modAccessPolicy.php
  core/src/Revolution/modAccessPolicyTemplate.php
  core/src/Revolution/modAccessPolicyTemplateGroup.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/security/modx.combo.access.policy.template.groups.js
  manager/assets/modext/widgets/security/modx.grid.access.policy.js
  manager/assets/modext/widgets/security/modx.grid.access.policy.template.js
  manager/assets/modext/widgets/security/modx.panel.access.policy.js
  manager/assets/modext/widgets/security/modx.panel.access.policy.template.js
  manager/assets/modext/widgets/security/modx.panel.groups.roles.js
  manager/controllers/default/security/access/policy/template/update.class.php
  manager/controllers/default/security/permission.class.php
  setup/includes/upgrades/common/3.0-policy-description.php
  setup/includes/upgrades/common/3.0-policy-template-description.php
  setup/includes/upgrades/common/3.0-policy-template-group-description.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: area-i18n/l10n, cla-signed, enhancement, pr-state/ready-for-merging

#15489 Removed TV with "list-multiple-legacy" type
  core/lexicon/en/tv_input_types.inc.php
  core/lexicon/en/tv_widget.inc.php
  core/src/Revolution/Processors/Element/TemplateVar/Renders/mgr/input/list-multiple-legacy.class.php
  core/src/Revolution/Processors/Element/TemplateVar/Renders/mgr/inputproperties/list-multiple-legacy.php
  manager/assets/modext/widgets/element/modx.panel.tv.js
  manager/templates/default/element/tv/renders/input/list-multiple-legacy.tpl
  manager/templates/default/element/tv/renders/inputproperties/list-multiple-legacy.tpl
  setup/includes/upgrades/common/3.0.0-cleanup-files.php
  setup/includes/upgrades/common/3.0.0-update-tvs-list-legacy.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: area-ux/ui, cla-signed, enhancement, pr-state/ready-for-merging

#15566 Update Smarty to 3.1.39
  core/model/smarty/Smarty.class.php
  core/model/smarty/SmartyBC.class.php
  core/model/smarty/sysplugins/smarty_internal_compile_function.php
  core/model/smarty/sysplugins/smarty_internal_compile_private_special_variable.php
  core/model/smarty/sysplugins/smarty_internal_config_file_compiler.php
  core/model/smarty/sysplugins/smarty_internal_errorhandler.php
  core/model/smarty/sysplugins/smarty_internal_parsetree_template.php
Labels: cla-signed, pr-state/ready-for-merging

#15554 Changing display styles for system information
  _build/templates/default/sass/_dashboard.scss
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: area-ux/ui, cla-signed, pr-state/ready-for-merging

#15539 Corrected fields in the User / Account sections
  _build/templates/default/sass/_forms.scss
  manager/assets/modext/sections/security/profile/update.js
  manager/assets/modext/widgets/security/modx.panel.user.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: area-ux/ui, cla-signed, pr-state/ready-for-merging

#15516 Implement isDirty function in MODx.panel.ImageTV
  manager/assets/modext/widgets/element/modx.panel.tv.renders.js
Labels: cla-signed, pr-state/ready-for-merging

#15562 Update information about the project in the readme file
  README.md
Labels: cla-signed

#15589 Increases the basic required version of php
  .github/workflows/ci.yml
  composer.json
Labels: cla-signed, pr-state/review-needed

#15457 Add transliteration of files when uploading to a media source #modxbughunt
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/src/Revolution/Sources/modMediaSource.php
Labels: cla-signed, pr-state/ready-for-merging

#15599 Fix Add button style glitches in dashboards
  _build/templates/default/sass/_dashboard.scss
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: area-ux/ui, cla-signed, pr-state/ready-for-merging

#15420 Simplified lexicons for grids
  core/lexicon/en/access.inc.php
  core/lexicon/en/content_type.inc.php
  core/lexicon/en/context.inc.php
  core/lexicon/en/dashboards.inc.php
  core/lexicon/en/default.inc.php
  core/lexicon/en/events.inc.php
  core/lexicon/en/file.inc.php
  core/lexicon/en/formcustomization.inc.php
  core/lexicon/en/lexicon.inc.php
  core/lexicon/en/menu.inc.php
  core/lexicon/en/messages.inc.php
  core/lexicon/en/namespace.inc.php
  core/lexicon/en/plugin.inc.php
  core/lexicon/en/policy.inc.php
  core/lexicon/en/resource.inc.php
  core/lexicon/en/setting.inc.php
  core/lexicon/en/source.inc.php
  core/lexicon/en/user.inc.php
  core/lexicon/en/workspace.inc.php
  core/src/Revolution/Processors/Element/Plugin/Event/GetList.php
  core/src/Revolution/Processors/Workspace/Providers/GetList.php
  core/src/Revolution/Sources/modMediaSource.php
  manager/assets/modext/sections/context/view.js
  manager/assets/modext/sections/security/role/list.js
  manager/assets/modext/sections/security/user/update.js
  manager/assets/modext/widgets/core/modx.grid.settings.js
  manager/assets/modext/widgets/element/modx.grid.plugin.event.js
  manager/assets/modext/widgets/element/modx.grid.template.tv.js
  manager/assets/modext/widgets/fc/modx.grid.fcprofile.js
  manager/assets/modext/widgets/fc/modx.grid.fcset.js
  manager/assets/modext/widgets/fc/modx.panel.fcset.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
  manager/assets/modext/widgets/security/modx.grid.access.context.js
  manager/assets/modext/widgets/security/modx.grid.access.policy.js
  manager/assets/modext/widgets/security/modx.grid.access.policy.template.js
  manager/assets/modext/widgets/security/modx.grid.message.js
  manager/assets/modext/widgets/security/modx.grid.role.js
  manager/assets/modext/widgets/security/modx.grid.user.group.settings.js
  manager/assets/modext/widgets/security/modx.grid.user.js
  manager/assets/modext/widgets/security/modx.grid.user.settings.js
  manager/assets/modext/widgets/security/modx.panel.access.policy.template.js
  manager/assets/modext/widgets/source/modx.grid.source.properties.js
  manager/assets/modext/widgets/source/modx.panel.sources.js
  manager/assets/modext/widgets/system/modx.grid.content.type.js
  manager/assets/modext/widgets/system/modx.grid.context.js
  manager/assets/modext/widgets/system/modx.grid.context.settings.js
  manager/assets/modext/widgets/system/modx.grid.dashboard.widgets.js
  manager/assets/modext/widgets/system/modx.grid.system.event.js
  manager/assets/modext/widgets/system/modx.panel.dashboards.js
  manager/assets/modext/widgets/system/modx.tree.menu.js
  manager/assets/modext/widgets/windows.js
  manager/assets/modext/workspace/lexicon/lexicon.grid.js
  manager/assets/modext/workspace/namespace/modx.namespace.panel.js
  manager/assets/modext/workspace/provider.grid.js
  manager/controllers/default/security/user/create.class.php
Labels: cla-signed, pr-state/ready-for-merging

#15591 Changing the lexicon on the update widget
  core/lexicon/en/dashboard.inc.php
  manager/templates/default/dashboard/updates.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15572 Update base_help_url system settings with a new link to the documentation
  _build/data/transport.core.system_settings.php
  setup/includes/upgrades/common/3.0.0-update-sys-setting_base_help_url.php
Labels: cla-signed, pr-state/ready-for-merging

#15478 Hide dependent forms until items are not selected in trees
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/element/modx.panel.property.set.js
  manager/assets/modext/widgets/security/modx.panel.user.js
  manager/assets/modext/widgets/system/modx.panel.dashboard.widget.js
Labels: cla-signed, enhancement, pr-state/ready-for-merging

#15482 Fix trash page permission issues
  _build/data/transport.core.accesspolicies.php
  core/src/Revolution/Processors/Resource/Trash/GetList.php
Labels: cla-signed, pr-state/ready-for-merging

#15600 Fix the lexicon entries of upload_translit
  core/lexicon/en/setting.inc.php
Labels: area-i18n/l10n, cla-signed, pr-state/review-needed

#15571 Updating url in system setting base_help_url
  _build/data/transport.core.system_settings.php
  setup/includes/upgrades/common/2.8.2-update-base_help_url.php
Labels: cla-signed, pr-state/ready-for-merging

#15527 Improve the lexicon entry for mail_smtp_prefix
  core/lexicon/en/setting.inc.php
Labels: area-i18n/l10n, cla-signed, pr-state/port-to-3.x, pr-state/ready-for-merging

#15534 Implement isDirty function in MODx.panel.ImageTV and MODx.panel.FileTV
  manager/assets/modext/widgets/element/modx.panel.tv.renders.js
Labels: cla-signed, pr-state/ready-for-merging

#15593 Fixed context sub-menu not appearing in resource tree
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
Labels: cla-signed, pr-state/ready-for-merging

#15079 Remove deprecated modClassMap
  core/model/schema/modx.mysql.schema.xml
  core/model/schema/modx.sqlsrv.schema.xml
  core/src/Revolution/Processors/Element/GetClasses.php
  core/src/Revolution/Processors/System/ClassMap/GetList.php
  core/src/Revolution/metadata.mysql.php
  core/src/Revolution/metadata.sqlsrv.php
  core/src/Revolution/modClassMap.php
  core/src/Revolution/mysql/modClassMap.php
  core/src/Revolution/sqlsrv/modClassMap.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.combo.js
  setup/includes/tables_create.php
  setup/includes/upgrades/common/3.0.0-cleanup-files.php
Labels: cla-signed, pr-state/ready-for-merging

#15608 Ignore l10n_** branches on ci workflow actions
  .github/workflows/ci.yml
Labels: cla-signed, pr-state/ready-for-merging

#15609 Ignore l10n_** branches on ci workflow actions
  .github/workflows/ci.yml
Labels: cla-signed, pr-state/ready-for-merging

#15594 Fixed dummy data for the makeUrl method
  _build/test/Tests/Cases/Request/MakeUrlTest.php
Labels: bug, cla-signed, pr-state/review-needed
