Repository modxcms/revolution, pull requests merged in 2021-08, with the labels that each got.

#15629 Returned the method to display the password in "User" section
  core/lexicon/en/user.inc.php
  manager/assets/modext/widgets/security/modx.panel.user.js
Labels: pr/ready-for-merging, cla-signed

#15758 Corrected styles for right-to-left text direction
  _build/templates/default/sass/_buttons.scss
  _build/templates/default/sass/_dashboard.scss
  _build/templates/default/sass/_forms.scss
  _build/templates/default/sass/_navbar.scss
  _build/templates/default/sass/_tabs.scss
  _build/templates/default/sass/_tree.scss
  _build/templates/default/sass/_xtheme-modx.scss
  _build/templates/default/sass/index.scss
  manager/assets/modext/core/modx.layout.js
  manager/assets/modext/modx.jsgrps-min.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: type-frontend, area-a11y, pr/review-needed, cla-signed

#15781 [BC] Refactor modTransportProvider to PSR-7 requests, remove modRestClient
  core/src/Revolution/Rest/modRestClient.php
  core/src/Revolution/Rest/modRestCurlClient.php
  core/src/Revolution/Rest/modRestResponse.php
  core/src/Revolution/Rest/modRestSockClient.php
  core/src/Revolution/Transport/modTransportProvider.php
  core/src/Revolution/modX.php
  setup/includes/upgrades/common/3.0.0-cleanup-files.php
Labels: cla-signed

#15786 Reworking the S3 System to return objects
  core/src/Revolution/Sources/modS3MediaSource.php
Labels: pr/review-needed, cla-signed

#15803 Prevent line lengths over 120 from throwing errors
  .github/workflows/phpcs.yml
Labels: cla-signed
