Repository modxcms/revolution, pull requests merged in 2021-11, with the labels that each got.

#15882 [3.x] Remove unused refreshTVs method
  manager/assets/modext/widgets/resource/modx.panel.resource.tv.js
  manager/templates/default/resource/sections/tvs.tpl
Labels: pr/ready-for-merging, cla-signed

#15885 Restrict static resources to predefined path (port of #15656 for 3.x, SEC-3801)
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/src/Revolution/modStaticResource.php
Labels: cla-signed

#15890 [Port to 3.x] Add new config option for number TVs
  core/lexicon/en/tv_widget.inc.php
  core/src/Revolution/Processors/Element/TemplateVar/Configs/mgr/inputproperties/number.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/util/utilities.js
  manager/templates/default/element/tv/renders/input/number.tpl
Labels: pr/review-needed, cla-signed

#15883 Removing a stray <p> tag.
  core/lexicon/en/resource.inc.php
Labels: pr/ready-for-merging, cla-signed

#15884 Remove superfluous lexicon entries
  core/lexicon/en/tv_widget.inc.php
Labels: pr/ready-for-merging, cla-signed

#15900 [2.x] Fix isBinary check to correctly indicate certain textual formats as being not binary
  core/model/modx/modfilehandler.class.php
Labels: cla-signed

#15901 [3.x] Fix binary checks (port of #15900) to make sure textual-ish files can be edited
  core/src/Revolution/Sources/modMediaSource.php
Labels: cla-signed

#15910 Remove unused processor Security/User/Group/GetList
  core/src/Revolution/Processors/Security/User/Group/GetList.php
  setup/includes/upgrades/common/3.0.0-cleanup-files.php
Labels: pr/ready-for-merging, cla-signed

#15759 Change order of menu items for Directory/File in tree
  core/lexicon/en/file.inc.php
  core/src/Revolution/Sources/modMediaSource.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/element/modx.tree.element.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
Labels: type-frontend, pr/ready-for-merging, cla-signed
