Repository modxcms/revolution, pull requests merged in 2021-02, with the labels that each got.

#15367 Improve removal of nested MODX tag content in sanitizeRequest
  _build/test/Tests/Model/Request/modRequestTest.php
  core/docs/changelog.txt
  core/model/modx/modx.class.php
Labels: area-core, bug, cla-signed

#15218 Changed options for TV output with url type
  core/src/Revolution/Processors/Element/TemplateVar/Renders/web/output/url.class.php
  manager/templates/default/element/tv/renders/properties/url.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15369 Typo in test
  _build/test/Tests/Model/Request/modRequestTest.php
Labels: cla-signed, pr-state/ready-for-merging

#15370 Improve removal of nested MODX tag content in sanitizeRequest
  _build/test/Tests/Model/Request/modRequestTest.php
  core/docs/changelog.txt
  core/src/Revolution/modX.php
Labels: bug, cla-signed

#15208 Removed unused options for TV output with image type
  core/lexicon/en/tv_widget.inc.php
  core/src/Revolution/Processors/Element/TemplateVar/Renders/web/output/image.class.php
  manager/templates/default/element/tv/renders/properties/image.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15163 Fix a fatal error when calling runProcessor in a connector
  core/src/Revolution/modX.php
Labels: cla-signed, pr-state/review-needed

#15308 Only log session info if session is initialized
  core/docs/changelog.txt
  core/src/Revolution/modSessionHandler.php
Labels: cla-signed, pr-state/review-needed

#15372 Fix classes used by property sets
  core/src/Revolution/Processors/Element/GetClasses.php
  manager/assets/modext/widgets/element/modx.panel.plugin.js
  manager/assets/modext/widgets/element/modx.panel.property.set.js
  manager/assets/modext/widgets/element/modx.panel.snippet.js
  manager/assets/modext/widgets/element/modx.panel.template.js
  manager/assets/modext/widgets/element/modx.panel.tv.js
Labels: cla-signed

#15152 Changed the output template for menu items
  _build/data/transport.core.menus.php
  _build/templates/default/sass/_navbar.scss
  core/lexicon/en/topmenu.inc.php
  manager/controllers/default/header.php
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
  setup/includes/upgrades/common/3.0.0-update-menu-main.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: cla-signed, pr-state/ready-for-merging

#15385 Fix downloading files
  core/src/Revolution/Processors/Browser/File/Download.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/system/modx.tree.directory.js
Labels: cla-signed, pr-state/review-needed

#15261 Decreased z-index for collapse icon in resource form
  _build/templates/default/sass/index.scss
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: cla-signed, pr-state/ready-for-merging

#15286 Making a file active if context menu is called for it
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/media/modx.browser.js
Labels: cla-signed, pr-state/ready-for-merging

#15312 Remove flash based xtypes
  manager/assets/ext3/ext-all-debug.js
  manager/assets/ext3/ext-all.js
  manager/assets/fileapi/FileAPI.js
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/util/utilities.js
Labels: cla-signed, pr-state/ready-for-merging

#15378 Avoid returning resource_groups on resource save
  core/src/Revolution/Processors/Resource/Update.php
Labels: cla-signed, pr-state/ready-for-merging

#15379 Fixed incorrect behavior for resource form checkboxes "alias_visible" and "syncsite"
  manager/controllers/default/resource/create.class.php
  manager/controllers/default/resource/update.class.php
Labels: cla-signed, pr-state/ready-for-merging

#15380 Fixed PHP notice "Undefined index" for resources without a template
  manager/controllers/default/resource/resource.class.php
Labels: cla-signed, pr-state/ready-for-merging

#15381 Fix bug in the resource trash interface
  core/src/Revolution/Processors/Resource/Trash/GetList.php
Labels: cla-signed, pr-state/ready-for-merging

#15382 Fix uninstalling package error message
  core/src/Revolution/Processors/Workspace/Packages/Uninstall.php
Labels: cla-signed, pr-state/ready-for-merging

#15383 Allow directories with name "0"
  core/src/Revolution/Processors/Browser/Directory/Create.php
  core/src/Revolution/Processors/Browser/Directory/Remove.php
  core/src/Revolution/Processors/Browser/Directory/Rename.php
  core/src/Revolution/Processors/Browser/Directory/Sort.php
Labels: cla-signed, pr-state/ready-for-merging

#15394 Quote a principal_class value
  core/src/Revolution/modResource.php
Labels: cla-signed, pr-state/ready-for-merging

#15396 Add composer script to parse modx schema
  composer.json
Labels: cla-signed, pr-state/review-needed

#15335 PHP 8 Compatibility
  core/model/modx/modtemplatevar.class.php
  core/model/modx/transport/modtransportpackage.class.php
  core/model/phpthumb/phpthumb.bmp.php
  core/model/phpthumb/phpthumb.class.php
  core/model/phpthumb/phpthumb.filters.php
  core/model/phpthumb/phpthumb.functions.php
  core/xpdo/changelog.txt
  core/xpdo/compression/pclzip.lib.php
  core/xpdo/xpdo.class.php
  setup/includes/new.install.php
Labels: area-core, area-setup, cla-signed, priority-1-urgent

#15393 Allow calls to the session handler gc() to return number of removed sessions
  core/model/modx/modsessionhandler.class.php
Labels: cla-signed

#15400 Change modSessionHandler->gc() to return number of removed sessions
  core/src/Revolution/modSessionHandler.php
Labels: area-core, bug, cla-signed

#15401 Fix fatal error: "Uncaught Error: Call to undefined function get_magic_quotes_gpc()" on PHP8
  core/model/modx/modx.class.php
Labels: cla-signed

#15408 [3.x] Fix plugin's event property sets
  manager/assets/modext/widgets/element/modx.grid.plugin.event.js
Labels: cla-signed, pr-state/review-needed

#15406 Changed the default gravatar type
  core/src/Revolution/modUser.php
Labels: area-ux/ui, cla-signed, pr-state/ready-for-merging

#15405 Changed logo in base template
  setup/templates/base_template.tpl
Labels: cla-signed, pr-state/port-to-3.x, pr-state/ready-for-merging

#15404 [3.x] Fix fatal error: "Uncaught Error: Call to undefined function get_magic_quotes_gpc()" on PHP8
  core/src/Revolution/modX.php
Labels: cla-signed, pr-state/ready-for-merging

#15403 [3.x] Improve the processor permission response error message
  core/lexicon/en/default.inc.php
  core/src/Revolution/Processors/ModelProcessor.php
  core/src/Revolution/Processors/Processor.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.combo.js
Labels: cla-signed, enhancement, pr-state/ready-for-merging

#15402 Improve the processor permission response error message
  core/lexicon/en/default.inc.php
  core/model/modx/modprocessor.class.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.combo.js
Labels: cla-signed, enhancement, pr-state/port-to-3.x, pr-state/review-needed

#15267 Added check for package exist when uploading it
  _build/templates/default/sass/index.scss
  core/lexicon/en/file.inc.php
  core/src/Revolution/Processors/Workspace/Packages/Upload.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
  manager/templates/default/fonts/fa-brands-400.eot
  manager/templates/default/fonts/fa-brands-400.svg
  manager/templates/default/fonts/fa-brands-400.ttf
  manager/templates/default/fonts/fa-brands-400.woff
  manager/templates/default/fonts/fa-brands-400.woff2
  manager/templates/default/fonts/fa-regular-400.eot
  manager/templates/default/fonts/fa-regular-400.svg
  manager/templates/default/fonts/fa-regular-400.ttf
  manager/templates/default/fonts/fa-regular-400.woff
  manager/templates/default/fonts/fa-regular-400.woff2
  manager/templates/default/fonts/fa-solid-900.eot
  manager/templates/default/fonts/fa-solid-900.svg
  manager/templates/default/fonts/fa-solid-900.ttf
  manager/templates/default/fonts/fa-solid-900.woff
  manager/templates/default/fonts/fa-solid-900.woff2
  setup/assets/css/installer-min.css
  setup/assets/css/installer.css
Labels: cla-signed, pr-state/ready-for-merging

#15149 Reordered the navigation tabs in the "User Group"
  core/lexicon/en/access.inc.php
  manager/assets/modext/widgets/security/modx.panel.user.group.js
Labels: cla-signed, pr-state/ready-for-merging

#15229 Fixed collapsing tree on mobile screens
  manager/assets/modext/core/modx.layout.js
  manager/assets/modext/modx.jsgrps-min.js
Labels: cla-signed, pr-state/ready-for-merging

#15346 JsonGrid fixes
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.grid.js
Labels: cla-signed, pr-state/ready-for-merging

#15389 User extended properties - fix rendering value
  manager/assets/modext/widgets/core/modx.orm.js
Labels: cla-signed, pr-state/ready-for-merging

#15391 Fix breadcrumbs on new resources
  manager/assets/modext/widgets/resource/modx.panel.resource.js
  manager/controllers/default/resource/create.class.php
  manager/controllers/default/resource/resource.class.php
  manager/controllers/default/resource/update.class.php
Labels: cla-signed, pr-state/ready-for-merging

#15413 Fix country name in the user section is not always displayed
  core/src/Revolution/Processors/System/Country/GetList.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.combo.js
  manager/assets/modext/widgets/security/modx.panel.user.js
Labels: cla-signed, pr-state/ready-for-merging
