Repository modxcms/revolution, pull requests merged in 2021-04, with the labels that each got.

#15603 Add code quality GitHub Action
  .github/workflows/phpcs.yml
Labels: Idea 💡, cla-signed, pr-state/ready-for-merging

#15620 Fix class key default value in the user creation form
  manager/assets/modext/widgets/security/modx.panel.user.js
Labels: bug, cla-signed, pr-state/ready-for-merging

#15618 Update PHPMailer to 6.4.0
  core/model/modx/mail/phpmailer/README.md
  core/model/modx/mail/phpmailer/SECURITY.md
  core/model/modx/mail/phpmailer/VERSION
  core/model/modx/mail/phpmailer/composer.json
  core/model/modx/mail/phpmailer/get_oauth_token.php
  core/model/modx/mail/phpmailer/language/phpmailer.lang-sr_latn.php
  core/model/modx/mail/phpmailer/src/PHPMailer.php
  core/model/modx/mail/phpmailer/src/POP3.php
  core/model/modx/mail/phpmailer/src/SMTP.php
Labels: cla-signed, pr-state/ready-for-merging

#15611 Add missing user password validation characters
  core/lexicon/en/user.inc.php
Labels: area-i18n/l10n, cla-signed

#15633 Automatically mark issues by appropriate labels
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: backport, cla-signed, pr-state/ready-for-merging

#15578 Add the EXTR_REFS flag to the extract function
  core/src/Revolution/modScript.php
Labels: cla-signed, pr-state/ready-for-merging, proposal

#15602 Update favicon in the installation folder
  setup/favicon.ico
Labels: cla-signed, pr-state/ready-for-merging

#15613 Fix link to the proper version in welcome dialog
  _build/data/transport.core.system_settings.php
  setup/includes/upgrades/common/3.0.0-update-sys-setting_base_help_url.php
  setup/includes/upgrades/common/3.0.0-update-sys-setting_welcome_screen_url.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: cla-signed, pr-state/ready-for-merging

#15621 Fix unavailable toggle language menu item because missed permission
  _build/data/transport.core.accesspolicies.php
Labels: cla-signed, pr-state/ready-for-merging

#15632 Fix permissions checking in modAccessibleObject objects
  core/src/Revolution/modCategory.php
  core/src/Revolution/modContext.php
  core/src/Revolution/modElement.php
  core/src/Revolution/modNamespace.php
  core/src/Revolution/modResource.php
  core/src/Revolution/modTemplateVar.php
Labels: area-acl, cla-signed, pr-state/ready-for-merging

#15635 Automatically mark issues by appropriate labels
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla-signed, pr-state/ready-for-merging

#15626 Fix missed Developer Access Policy
  _build/resolvers/resolve.policies.php
  core/src/Revolution/modAccessPolicy.php
  setup/includes/upgrades/common/3.0.0-policy-description.php
  setup/includes/upgrades/common/3.0.0-policy-template-description.php
  setup/includes/upgrades/common/3.0.0-policy-template-group-description.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
  setup/includes/upgrades/sqlsrv/3.0.0-pl.php
Labels: cla-signed, pr-state/ready-for-merging

#15628 Fix access policy template group name
  manager/assets/modext/widgets/security/modx.grid.user.group.context.js
  manager/assets/modext/widgets/security/modx.panel.user.group.js
  manager/assets/modext/widgets/security/modx.tree.user.group.js
Labels: area-security, cla-signed, pr-state/ready-for-merging

#15644 Prevent XSSI access to `MODx.config` by requiring the auth token to be present
  connectors/modx.config.js.php
  core/model/modx/modmanagercontroller.class.php
  core/model/modx/processors/system/config.js.class.php
  manager/templates/default/header.tpl
Labels: area-security, cla-signed, pr-state/review-needed, urgent

#15638 Incorrect use of the getOption method
  core/src/Revolution/modResource.php
Labels: cla-signed, pr-state/ready-for-merging

#15640 Add PHP Code Sniffer configuration file
  phpcs.xml
Labels: cla-signed, pr-state/ready-for-merging, proposal

#15643 Restrict file management to allowed file types [SEC-3837]
  core/model/modx/sources/modfilemediasource.class.php
  core/model/modx/sources/mods3mediasource.class.php
Labels: area-security, cla-signed, pr-state/port-to-3.x, pr-state/review-needed, urgent

#15647 Fix invalid getOption call in modResource->filterPathSegment
  core/model/modx/modresource.class.php
Labels: area-core, bug, cla-signed, pr-state/ready-for-merging

#15646 Remove legacy file manager processors [SEC-3837]
  core/model/modx/processors/system/filesys/file/remove.php
  core/model/modx/processors/system/filesys/file/unzip.php
  core/model/modx/processors/system/filesys/file/update.php
  core/model/modx/processors/system/filesys/folder/create.php
  core/model/modx/processors/system/filesys/folder/remove.php
  setup/includes/upgrades/common/2.8.2-remove-processors.php
  setup/includes/upgrades/mysql/2.8.2-pl.php
  setup/includes/upgrades/sqlsrv/2.8.2-pl.php
Labels: area-security, cla-signed, pr-state/ready-for-merging, urgent

#15418 Strip base_url only from beginning of relative url
  manager/assets/modext/widgets/resource/modx.panel.resource.static.js
Labels: cla-signed, pr-state/port-to-3.x

#15641 Add endpoint property to S3 media source
  core/lexicon/en/source.inc.php
  core/src/Revolution/Sources/modS3MediaSource.php
Labels: area-core, cla-signed

#15652 Add clarity within creating folders in media sources
  core/lexicon/en/file.inc.php
  core/lexicon/en/source.inc.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/system/modx.tree.directory.js
Labels: area-ux/ui, cla-signed, feature, pr-state/ready-for-merging

#15642 Fix style of information messages in installer view
  _build/templates/default/sass/installer.scss
  setup/assets/css/installer-min.css
  setup/assets/css/installer.css
  setup/templates/summary.tpl
Labels: cla-signed, pr-state/ready-for-merging

#15537 Add possibility to translate message about site unavailability
  _build/data/transport.core.system_settings.php
  core/lexicon/en/default.inc.php
  core/model/schema/modx.mysql.schema.xml
  core/model/schema/modx.sqlsrv.schema.xml
  core/src/Revolution/mysql/modTemplate.php
  core/src/Revolution/sqlsrv/modTemplate.php
Labels: area-i18n/l10n, area-ux/ui, cla-signed, pr-state/ready-for-merging

#15627 Improve language selector accessibility on the login page
  manager/templates/default/security/login.tpl
Labels: area-a11y, cla-signed, pr-state/ready-for-merging

#15259 Add intermediate tablet breakpoint to improve view on small screens
  _build/templates/default/sass/_colors-and-vars.scss
  _build/templates/default/sass/_navbar.scss
  _build/templates/default/sass/_tree.scss
  _build/templates/default/sass/index.scss
  manager/assets/modext/core/modx.layout.js
  manager/assets/modext/modx.jsgrps-min.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: cla-signed, pr/ready-for-merging

#15398 Switch non-index fields back to 255 char limit
  core/model/schema/modx.mysql.schema.xml
  core/src/Revolution/Registry/Db/sqlsrv/modDbRegisterMessage.php
  core/src/Revolution/Transport/mysql/modTransportPackage.php
  core/src/Revolution/Transport/sqlsrv/modTransportPackage.php
  core/src/Revolution/mysql/modAccessPolicy.php
  core/src/Revolution/mysql/modAccessPolicyTemplate.php
  core/src/Revolution/mysql/modActionDom.php
  core/src/Revolution/mysql/modActionField.php
  core/src/Revolution/mysql/modActiveUser.php
  core/src/Revolution/mysql/modChunk.php
  core/src/Revolution/mysql/modContextSetting.php
  core/src/Revolution/mysql/modDashboardWidget.php
  core/src/Revolution/mysql/modDashboardWidgetPlacement.php
  core/src/Revolution/mysql/modExtensionPackage.php
  core/src/Revolution/mysql/modFormCustomizationSet.php
  core/src/Revolution/mysql/modManagerLog.php
  core/src/Revolution/mysql/modMenu.php
  core/src/Revolution/mysql/modPlugin.php
  core/src/Revolution/mysql/modPropertySet.php
  core/src/Revolution/mysql/modResource.php
  core/src/Revolution/mysql/modScript.php
  core/src/Revolution/mysql/modSnippet.php
  core/src/Revolution/mysql/modSystemSetting.php
  core/src/Revolution/mysql/modTemplate.php
  core/src/Revolution/mysql/modTemplateVar.php
  core/src/Revolution/mysql/modUserGroupSetting.php
  core/src/Revolution/mysql/modUserMessage.php
  core/src/Revolution/mysql/modUserProfile.php
  core/src/Revolution/mysql/modUserSetting.php
  core/src/Revolution/mysql/modWorkspace.php
  manager/assets/modext/widgets/element/modx.panel.chunk.js
  manager/assets/modext/widgets/element/modx.panel.plugin.js
  manager/assets/modext/widgets/element/modx.panel.snippet.js
  manager/assets/modext/widgets/element/modx.panel.template.js
  manager/assets/modext/widgets/fc/modx.panel.fcprofile.js
  manager/assets/modext/widgets/resource/modx.panel.resource.js
  manager/assets/modext/widgets/system/modx.panel.context.js
  setup/includes/upgrades/common/3.0.0-non-index-field-length.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
Labels: cla-signed, pr/ready-for-merging

#15612 Add return link to package management on a page of single package
  manager/assets/modext/workspace/package/package.panel.js
Labels: cla-signed, pr/review-needed

#15511 Fix issue when sending an internal message to the user
  core/src/Revolution/Processors/Security/Message/Create.php
  manager/assets/modext/widgets/security/modx.grid.message.js
Labels: bug, cla-signed, pr/review-needed

#15650 Fix the appearance of PHP notices on the dashboard page
  manager/templates/default/dashboard/recentlyeditedresources.tpl
Labels: bug, cla-signed, pr/ready-for-merging

#15668 Fix ignoring config phpcs
  .github/workflows/phpcs.yml
Labels: cla-signed, proposal

#15670 Set code of conduct for the repository
  CODE_OF_CONDUCT.md
Labels: cla-signed, pr/port-to-3

#15671 Set code of conduct for the repo
  CODE_OF_CONDUCT.md
Labels: cla-signed

#15666 MODX Session Cookie with SameSite
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/model/modx/modx.class.php
Labels: area-core, area-security, cla-signed, feature, needs-docs, pr/port-to-3, pr/review-needed

#15669 allow usage of samesite cookie setting since PHP 7.3.0
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/src/Revolution/modX.php
Labels: area-core, area-security, cla-signed, feature, pr/review-needed

#15656 Restrict static resources to predefined path [SEC-3801]
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/model/modx/modstaticresource.class.php
Labels: area-security, cla-signed, pr/review-needed, urgent

#15655 Add permissions to enforce access to specific resource types [SEC-3811]
  _build/data/permissions/transport.policy.tpl.administrator.php
  _build/data/transport.core.accesspolicies.php
  core/lexicon/en/permissions.inc.php
  core/model/modx/modmanagercontroller.class.php
  core/model/modx/processors/resource/create.class.php
  core/model/modx/processors/resource/delete.class.php
  core/model/modx/processors/resource/update.class.php
  manager/controllers/default/resource/staticresource/create.class.php
  manager/controllers/default/resource/staticresource/update.class.php
  manager/controllers/default/resource/symlink/create.class.php
  manager/controllers/default/resource/symlink/update.class.php
  manager/controllers/default/resource/weblink/create.class.php
  manager/controllers/default/resource/weblink/update.class.php
Labels: area-security, cla-signed, pr/review-needed, urgent

#15490 Flatten the lexicon parameters by dot notation
  core/model/modx/modlexicon.class.php
Labels: blocked, cla-signed, pr/port-to-3

#15677 Prevent sensitive config values being available as [[++placeholders]] [SEC-3866]
  core/model/modx/modx.class.php
Labels: area-security, cla-signed, pr/port-to-3, pr/review-needed, urgent

#15678 Prevent authorized access to hashed user password, cachepwd, salt, and sessionid [SEC-3837]
  core/model/modx/processors/security/group/user/getlist.class.php
  core/model/modx/processors/security/user/duplicate.class.php
  core/model/modx/processors/security/user/get.class.php
  core/model/modx/processors/security/user/update.class.php
Labels: area-security, cla-signed, pr/port-to-3, pr/review-needed, urgent

#15532 LOG_LEVEL for cache errors
  core/model/modx/modcachemanager.class.php
Labels: area-core, cla-signed

#15693 Update PHPMailer 6.4.1
  core/model/modx/mail/phpmailer/SECURITY.md
  core/model/modx/mail/phpmailer/VERSION
  core/model/modx/mail/phpmailer/composer.json
  core/model/modx/mail/phpmailer/language/phpmailer.lang-uk.php
  core/model/modx/mail/phpmailer/src/PHPMailer.php
  core/model/modx/mail/phpmailer/src/POP3.php
  core/model/modx/mail/phpmailer/src/SMTP.php
Labels: area-core, area-security, cla-signed, urgent

#15692 Pass auth token to the config in the Browser controller
  manager/templates/default/browser/index.tpl
Labels: cla-signed, pr/port-to-3, pr/review-needed, urgent

#15699 Fix PHP 8 compatibility issues in modPHPThumb
  core/model/phpthumb/modphpthumb.class.php
Labels: area-core, bug, cla-signed, urgent
