Repository modxcms/revolution, pull requests merged in 2021-07, with the labels that each got.

#15481 #modxbughunt Fix displaying big SVG images in media browser
  core/src/Revolution/Sources/modMediaSource.php
Labels: cla-signed, pr/ready-for-merging

#15747 Fix import section lexicons
  manager/assets/modext/sections/system/import/html.js
  manager/assets/modext/sections/system/import/resource.js
  manager/controllers/default/system/import/index.class.php
Labels: area-lexicons, cla-signed, pr/ready-for-merging, type-frontend

#15749 Change order of menu items for Context in tree
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
Labels: cla-signed, pr/ready-for-merging, type-frontend

#15750 Update MODX logo in base template
  setup/templates/base_template.tpl
Labels: cla-signed, pr/ready-for-merging, type-frontend

#15751 Strip base_url only from beginning of relative url
  manager/assets/modext/widgets/resource/modx.panel.resource.static.js
Labels: area-core, cla-signed, pr/ready-for-merging

#15754 Filter sensitive config values from placeholders
  core/src/Revolution/modX.php
Labels: area-core, area-security, cla-signed, pr/ready-for-merging

#15755 Make naming consistent when duplicating user in grid
  core/src/Revolution/Processors/Security/User/Duplicate.php
Labels: cla-signed, pr/ready-for-merging, type-frontend

#15757 Upgrade flysystem to v2
  composer.json
  core/src/Revolution/Sources/modFTPMediaSource.php
  core/src/Revolution/Sources/modFileMediaSource.php
  core/src/Revolution/Sources/modMediaSource.php
  core/src/Revolution/Sources/modS3MediaSource.php
Labels: cla-signed

#15753 [port to 3.x] Changed LOG_LEVEL for cache errors
  core/src/Revolution/modCacheManager.php
Labels: area-core, cla-signed, pr/ready-for-merging

#15768 Update minimum PHP version to 7.2 in setup requirements
  setup/provisioner/requirements.php
Labels: cla-signed

#15769 Skip session configuration check in CLI setup
  setup/provisioner/bootstrap.php
Labels: cla-signed

#15645 Require auth token to access MODx.config to prevent XSSI
  connectors/modx.config.js.php
  core/src/Revolution/Processors/System/ConfigJs.php
  core/src/Revolution/modManagerController.php
  manager/templates/default/browser/index.tpl
  manager/templates/default/header.tpl
Labels: area-security, cla-signed, pr/ready-for-merging, urgent

#15630 Add missing user password validation characters
  core/lexicon/en/user.inc.php
Labels: cla-signed, pr/ready-for-merging

#15734 Add typeahead to Resource List TV
  manager/templates/default/element/tv/renders/input/resourcelist.tpl
  manager/templates/default/element/tv/renders/inputproperties/resourcelist.tpl
Labels: cla-signed, feature, pr/ready-for-merging, type-frontend

#15780 Leave Element/GetClasses processor alone
  setup/includes/upgrades/common/3.0.0-cleanup-files.php
Labels: cla-signed

#15779 Add PSR-7/17/18 HTTP services
  composer.json
  core/src/Revolution/modX.php
Labels: cla-signed, pr/review-needed

#15777 Assorted modRest improvements
  core/lexicon/en/workspace.inc.php
  core/src/Revolution/Rest/RestClientRequest.php
  core/src/Revolution/Rest/RestClientResponse.php
  core/src/Revolution/Rest/modRest.php
  core/src/Revolution/Transport/modTransportPackage.php
Labels: cla-signed
