Repository modxcms/revolution, pull requests merged in 2022-01, with the labels that each got.

#15959 Update xPDO to 3.0.1 for PHP 8.1 compatibility
  composer.json
Labels: cla-signed

#15960 Add PHP 8.1 to CI matrix
  .github/workflows/ci.yml
Labels: cla-signed

#15937 [3.x] Make validation error messaging consistent on save
  _build/templates/default/sass/_forms.scss
  manager/assets/modext/core/modx.component.js
  manager/assets/modext/core/modx.js
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/util/datetime.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
  manager/templates/default/css/login-min.css
  manager/templates/default/css/login.css
  manager/templates/default/element/tv/renders/input/autotag.tpl
  manager/templates/default/element/tv/renders/input/checkbox.tpl
  manager/templates/default/element/tv/renders/input/date.tpl
  manager/templates/default/element/tv/renders/input/email.tpl
  manager/templates/default/element/tv/renders/input/file.tpl
  manager/templates/default/element/tv/renders/input/hidden.tpl
  manager/templates/default/element/tv/renders/input/image.tpl
  manager/templates/default/element/tv/renders/input/listbox-multiple.tpl
  manager/templates/default/element/tv/renders/input/listbox-single.tpl
  manager/templates/default/element/tv/renders/input/number.tpl
  manager/templates/default/element/tv/renders/input/radio.tpl
  manager/templates/default/element/tv/renders/input/resourcelist.tpl
  manager/templates/default/element/tv/renders/input/richtext.tpl
  manager/templates/default/element/tv/renders/input/tag.tpl
  manager/templates/default/element/tv/renders/input/textarea.tpl
  manager/templates/default/element/tv/renders/input/textbox.tpl
  manager/templates/default/element/tv/renders/input/url.tpl
  setup/assets/css/installer-min.css
  setup/assets/css/installer.css
Labels: pr/ready-for-merging, cla-signed

#15868 Setup, contexts stage: fixes, simplifications, improvements
  _build/templates/default/sass/installer.scss
  setup/assets/css/installer-min.css
  setup/assets/css/installer.css
  setup/assets/js/sections/contexts.js
  setup/controllers/contexts.php
  setup/includes/request/modinstallrequest.class.php
  setup/templates/contexts.tpl
Labels: pr/ready-for-merging, cla-signed

#15888 Porting adding permissions to enforce access to specific resource types
  _build/data/permissions/transport.policy.tpl.administrator.php
  _build/data/transport.core.accesspolicies.php
  core/lexicon/en/permissions.inc.php
  core/src/Revolution/Processors/Resource/ActionAccessTrait.php
  core/src/Revolution/Processors/Resource/Create.php
  core/src/Revolution/Processors/Resource/Delete.php
  core/src/Revolution/Processors/Resource/Update.php
  core/src/Revolution/modManagerController.php
  core/src/Revolution/modParsedManagerController.php
  core/src/Revolution/modStaticResource.php
  core/src/Revolution/modSymLink.php
  core/src/Revolution/modWebLink.php
  manager/controllers/default/resource/create.class.php
  manager/controllers/default/resource/data.class.php
  manager/controllers/default/resource/staticresource/create.class.php
  manager/controllers/default/resource/staticresource/update.class.php
  manager/controllers/default/resource/symlink/create.class.php
  manager/controllers/default/resource/symlink/update.class.php
  manager/controllers/default/resource/update.class.php
  manager/controllers/default/resource/weblink/create.class.php
  manager/controllers/default/resource/weblink/update.class.php
Labels: pr/ready-for-merging, cla-signed

#15951 Fix missing labels and descriptions in TV quick create/edit window (revised)
  core/lexicon/en/default.inc.php
  core/lexicon/en/tv.inc.php
  core/lexicon/en/tv_widget.inc.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/windows.js
Labels: pr/ready-for-merging, cla-signed

#15955 [3.x] Form Customization: Grid editing erases set data
  core/src/Revolution/Processors/Security/Forms/Set/UpdateFromGrid.php
Labels: bug, area-fc, cla-signed

#15962 [3.x] Fix resource tree overflow on Firefox (and fix scrollbar color for Firefox Linux)
  _build/templates/default/sass/_tree.scss
  _build/templates/default/sass/index.scss
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/ready-for-merging, cla-signed

#15579 Added checks for pages specified in 'error_page' and 'site_unavailable_page' settings
  core/lexicon/en/resource.inc.php
  core/src/Revolution/Processors/Resource/Delete.php
  core/src/Revolution/Processors/Resource/Unpublish.php
  core/src/Revolution/Processors/Resource/Update.php
Labels: pr/review-needed, cla-signed

#15941 [3.x] Fix setup install tests from failing on sessions
  setup/includes/test/modinstalltest.class.php
Labels: cla-signed

#15889 [Port to 3.x] Form customization front end fixes/improvements
  _build/test/Tests/Model/FormCustomization/modActionDomTest.php
  core/src/Revolution/modActionDom.php
  manager/assets/modext/core/modx.js
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.panel.js
Labels: pr/review-needed, cla-signed

#15907 [3.x] Package Manager UX - loading mask
  core/lexicon/en/workspace.inc.php
  manager/assets/modext/workspace/package.grid.js
Labels: cla-signed

#15921 Fix setStaticElementPath method (port of #15912)
  manager/assets/modext/core/modx.js
  manager/assets/modext/widgets/element/modx.panel.chunk.js
  manager/assets/modext/widgets/element/modx.panel.plugin.js
  manager/assets/modext/widgets/element/modx.panel.snippet.js
  manager/assets/modext/widgets/element/modx.panel.template.js
  manager/assets/modext/widgets/element/modx.panel.tv.js
Labels: bug, pr/review-needed, cla-signed

#15956 Update category's rank in the tree after save
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/element/modx.tree.element.js
Labels: bug, pr/review-needed, cla-signed

#15961 Pass correct type to setlocale
  core/src/Revolution/modX.php
Labels: bug, area-core, cla-signed

#15926 [3.x] Fix combobox not expanding if processor response is slow
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.combo.js
Labels: pr/ready-for-merging, cla-signed

#15966 Fix undefined index in modMediaSource
  core/src/Revolution/Sources/modMediaSource.php
Labels: pr/ready-for-merging, cla-signed

#15970 Fix subsubnav position issue
  _build/templates/default/sass/_navbar.scss
  manager/controllers/default/header.php
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: bug, pr/ready-for-merging, cla-signed

#15624 Fix PHP warning: trim() expects parameter 1 to be string, array given
  core/src/Revolution/modTemplateVar.php
Labels: blocked, cla-signed

#15492 Flatten the lexicon parameters by dot notation
  core/src/Revolution/modLexicon.php
Labels: pr/review-needed, cla-signed

#15673 Simplified lexicons in grids
  core/lexicon/en/dashboards.inc.php
  core/lexicon/en/default.inc.php
  core/lexicon/en/element.inc.php
  core/lexicon/en/formcustomization.inc.php
  core/lexicon/en/lexicon.inc.php
  core/lexicon/en/manager_log.inc.php
  core/lexicon/en/namespace.inc.php
  core/lexicon/en/policy.inc.php
  core/lexicon/en/propertyset.inc.php
  core/lexicon/en/setting.inc.php
  core/lexicon/en/source.inc.php
  core/lexicon/en/topmenu.inc.php
  core/lexicon/en/user.inc.php
  manager/assets/modext/widgets/core/modx.grid.settings.js
  manager/assets/modext/widgets/element/modx.grid.element.properties.js
  manager/assets/modext/widgets/element/modx.grid.plugin.event.js
  manager/assets/modext/widgets/element/modx.grid.template.tv.js
  manager/assets/modext/widgets/element/modx.grid.tv.template.js
  manager/assets/modext/widgets/fc/modx.grid.fcprofile.js
  manager/assets/modext/widgets/fc/modx.grid.fcset.js
  manager/assets/modext/widgets/resource/modx.grid.trash.js
  manager/assets/modext/widgets/security/modx.grid.access.policy.js
  manager/assets/modext/widgets/security/modx.grid.access.policy.template.js
  manager/assets/modext/widgets/security/modx.grid.message.js
  manager/assets/modext/widgets/security/modx.grid.user.group.category.js
  manager/assets/modext/widgets/security/modx.grid.user.group.context.js
  manager/assets/modext/widgets/security/modx.grid.user.group.namespace.js
  manager/assets/modext/widgets/security/modx.grid.user.group.resource.js
  manager/assets/modext/widgets/security/modx.grid.user.group.source.js
  manager/assets/modext/widgets/security/modx.grid.user.js
  manager/assets/modext/widgets/security/modx.panel.user.group.js
  manager/assets/modext/widgets/source/modx.panel.sources.js
  manager/assets/modext/widgets/system/modx.grid.context.js
  manager/assets/modext/widgets/system/modx.grid.dashboard.widgets.js
  manager/assets/modext/widgets/system/modx.panel.dashboards.js
  manager/assets/modext/workspace/lexicon/lexicon.grid.js
  manager/assets/modext/workspace/namespace/modx.namespace.panel.js
  manager/assets/modext/workspace/package.grid.js
Labels: type-frontend, proposal, area-lexicons, pr/review-needed, cla-signed

#15977 Fix empty files considered non-existant (#15976)
  core/src/Revolution/Sources/modMediaSource.php
Labels: cla-signed

#15949 Remove duplicated curl option from request in modRest
  core/model/modx/rest/modrest.class.php
Labels: pr/ready-for-merging, cla-signed

#15898 Improve snippets logging in case error messages with arrays
  core/model/modx/modsnippet.class.php
Labels: pr/ready-for-merging, cla-signed

#15902 Switch resource_preview to resource_view
  core/lexicon/en/default.inc.php
  core/src/Revolution/Processors/Security/User/GetRecentlyEditedResources.php
  manager/assets/modext/widgets/resource/modx.tree.resource.js
Labels: pr/ready-for-merging, cla-signed

#15973 Displayed the username in user menu
  _build/data/transport.core.menus.php
  setup/includes/upgrades/common/3.0.0-update-menu-entries.php
Labels: type-frontend, pr/ready-for-merging, cla-signed

#15987 Fix Blank page when trying to create a Dashboard Widget
  manager/assets/modext/widgets/system/modx.panel.dashboard.widget.js
Labels: pr/ready-for-merging, cla-signed

#15994 [3.x Port] Use compare instead of assign
  manager/assets/modext/widgets/resource/modx.grid.trash.js
Labels: pr/ready-for-merging, cla-signed

#15997 Fix aliases for resource controllers
  manager/controllers/default/resource/create.class.php
  manager/controllers/default/resource/update.class.php
Labels: bug, pr/ready-for-merging, cla-signed

#15911 Fix Zend OPcache API warning when upgrading MODX
  setup/includes/modinstallsettings.class.php
  setup/index.php
Labels: pr/review-needed, cla-signed

#15978 Mark modX::parseChunk as deprecated (#12433)
  core/src/Revolution/modX.php
Labels: cla-signed

#15999 [3.x] Remove unnecessary uses of deprecated strftime()
  _build/test/properties.sample.inc.php
  _build/transport.core.php
  core/src/Revolution/Processors/Element/TemplateVar/Renders/mgr/input/date.class.php
  core/src/Revolution/Processors/Resource/Create.php
  core/src/Revolution/Processors/Resource/Event/UpdateFromGrid.php
  core/src/Revolution/Processors/Resource/Reload.php
  core/src/Revolution/Processors/Resource/Update.php
  core/src/Revolution/Processors/Security/Profile/Get.php
  core/src/Revolution/Processors/Security/User/Get.php
  core/src/Revolution/Processors/System/Info.php
  core/src/Revolution/Processors/System/Log/GetList.php
  core/src/Revolution/Processors/Workspace/Packages/ScanLocal.php
  core/src/Revolution/Registry/Db/mysql/modDbRegisterMessage.php
  core/src/Revolution/Registry/modDbRegister.php
  core/src/Revolution/Registry/modFileRegister.php
  core/src/Revolution/Transport/modTransportPackage.php
  core/src/Revolution/Transport/modTransportProvider.php
  core/src/Revolution/modExtensionPackage.php
  core/src/Revolution/modLexiconEntry.php
  core/src/Revolution/modWorkspace.php
  core/src/Revolution/modX.php
  setup/includes/modinstall.class.php
Labels: pr/review-needed, cla-signed

#15975 Improve stripmodxtags output filter
  core/src/Revolution/Filters/modOutputFilter.php
Labels: pr/review-needed, cla-signed

#15963 Improve stripmodxtags output filter
  core/model/modx/filters/modoutputfilter.class.php
Labels: cla-signed, pr/port-to-3

#15981 [3.x] Update permissions for viewing and clearing manager actions log
  _build/data/permissions/transport.policy.tpl.administrator.php
  _build/data/transport.core.accesspolicies.php
  _build/data/transport.core.menus.php
  core/lexicon/en/permissions.inc.php
  core/src/Revolution/Processors/System/Log/GetList.php
  core/src/Revolution/Processors/System/Log/Truncate.php
  manager/assets/modext/widgets/system/modx.grid.manager.log.js
  setup/includes/upgrades/common/3.0.0-remove-logs-permission.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
Labels: cla-signed

#16008 Fixed 'undefined' error if TV is located under content
  manager/assets/modext/widgets/resource/modx.panel.resource.js
Labels: type-frontend, pr/ready-for-merging, cla-signed
