Repository modxcms/revolution, pull requests merged in 2022-11, with the labels that each got.

#16291 Prevent errors or incompatibilities in extras from breaking the setup
  core/src/Revolution/modX.php
Labels: cla-signed

#16230 [Port to 3.x] Check if modx-content is defined before calling doLayout
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.grid.js
Labels: pr/review-needed, cla-signed

#16242 Fix rendering of user-entered values in editable listbox-multiple TVs
  core/src/Revolution/Processors/Element/TemplateVar/Renders/mgr/input/listbox-multiple.class.php
Labels: cla-signed

#16264 Fix MODX 3 installation for database passwords with backslashes and quotes
  setup/includes/runner/modinstallrunner.class.php
Labels: pr/review-needed, cla-signed

#16269 Avoid PHP warnings by only requiring deprecated.php once.
  core/model/modx/modx.class.php
Labels: cla-signed

#16271 Enable SVG thumbnail preview for image TVs
  _build/templates/default/sass/_forms.scss
  core/src/Revolution/Processors/System/PhpThumb.php
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/ready-for-merging, cla-signed

#16272 13970 ignore synlink
  _build/test/README.md
  _build/test/Tests/Processors/Browser/DirectoryTest.php
  core/src/Revolution/Sources/modFileMediaSource.php
Labels: pr/ready-for-merging, cla-signed

#16286 Exclude @SELECT binding from properties check in MODX 3
  core/src/Revolution/modTemplateVar.php
Labels: cla-signed

#16288 Refactor input filter parsing to properly support nested tags
  _build/test/Tests/Model/Filters/modInputFilterTest.php
  _build/test/Tests/Model/modParserTest.php
  core/src/Revolution/Filters/modInputFilter.php
  core/src/Revolution/Filters/modOutputFilter.php
Labels: urgent, cla-signed

#16292 Determine upload path based on the tree node's path attribute
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/system/modx.tree.directory.js
Labels: pr/review-needed, cla-signed

#16280 Remove the scrolling overflow from the modx-browser panel
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/media/modx.browser.js
Labels: cla-signed
