Repository modxcms/revolution, pull requests merged in 2022-03, with the labels that each got.

#16079 Fix typo on permission 'delete_static_resource'
  core/src/Revolution/Processors/Resource/Update.php
Labels: cla-signed

#16041 Enable popper for the submenu too (opens on hover)
  _build/templates/default/sass/_navbar.scss
  manager/assets/modext/core/modx.layout.js
  manager/assets/modext/modx.jsgrps-min.js
  manager/controllers/default/header.php
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/review-needed, cla-signed

#16085 Remove unnecessary underscore before /cache/
  core/lexicon/en/configcheck.inc.php
Labels: area-lexicons, pr/ready-for-merging, cla-signed

#16077 Update PHP versions in setup tests
  setup/includes/test/modinstalltest.class.php
  setup/provisioner/requirements.php
Labels: cla-signed

#16082 Update Element Panels' Static File/Preview Image UI
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.panel.js
  manager/assets/modext/widgets/element/modx.panel.chunk.js
  manager/assets/modext/widgets/element/modx.panel.plugin.js
  manager/assets/modext/widgets/element/modx.panel.snippet.js
  manager/assets/modext/widgets/element/modx.panel.template.js
  manager/assets/modext/widgets/element/modx.panel.tv.js
Labels: pr/ready-for-merging, cla-signed

#16088 Update xPDO to 3.1.0 and fix Container method signatures
  composer.json
  core/src/Revolution/Services/Container.php
Labels: cla-signed

#16090 Add a missing prefix to a setting lexicon entry
  core/lexicon/en/setting.inc.php
Labels: bug, pr/ready-for-merging, cla-signed

#16098 Revert static element logic to match 2.x branch
  _build/test/Tests/Model/Element/modStaticElementTest.php
  core/src/Revolution/Processors/Element/Create.php
  core/src/Revolution/Processors/Element/Update.php
  core/src/Revolution/modElement.php
Labels: bug, pr/review-needed, cla-signed

#16102 [3.x] Fix static file field visibility in legacy Element panel UIs
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.panel.js
  manager/assets/modext/widgets/element/modx.panel.template.js
Labels: pr/ready-for-merging, cla-signed

#16105 Prevent autofilling passwords where appropriate
  manager/assets/modext/widgets/security/modx.panel.user.js
  setup/templates/database.tpl
Labels: cla-signed

#16094 Fix incorrect word wrapping in manager panel
  _build/templates/default/sass/_tabs.scss
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/review-needed, cla-signed

#16087 Fix issue with non-standard ssl ports being removed from site URL
  core/docs/config.inc.tpl
  setup/includes/config/modconfigreader.class.php
  setup/provisioner/bootstrap.php
Labels: pr/review-needed, cla-signed
