Repository modxcms/revolution, pull requests merged in 2022-02, with the labels that each got.

#16016 Add consistent ?mv={version} cache busting suffix to prevent browser cache issues
  manager/templates/default/header.tpl
Labels: pr/ready-for-merging, cla-signed

#16002 Fix selecting parent in quick create resource
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
Labels: pr/ready-for-merging, cla-signed

#15974 Improve the regular expression for stripping remaining MODX tags
  core/src/Revolution/modDashboardWidgetInterface.php
Labels: bug, pr/review-needed, cla-signed

#15968 Adjust modUserGroup
  core/lexicon/en/user.inc.php
  core/model/schema/modx.mysql.schema.xml
  core/src/Revolution/Processors/Security/Group/GetNodes.php
  core/src/Revolution/Processors/Security/Group/Remove.php
  core/src/Revolution/Processors/Security/Group/Sort.php
  core/src/Revolution/Processors/Security/Group/Update.php
  core/src/Revolution/mysql/modUserGroup.php
  manager/assets/modext/widgets/security/modx.panel.user.group.js
  manager/assets/modext/widgets/security/modx.tree.user.group.js
Labels: pr/review-needed, cla-signed

#15996 [3.x Port] Configurable MessageBox minWidth
  manager/assets/modext/core/modx.js
Labels: pr/ready-for-merging, cla-signed

#16025 Avoid invalid UTF-8 characters breaking json_encode by applying JSON_INVALID_UTF8_SUBSTITUTE flag (#15796)
  core/src/Revolution/Processors/Browser/Directory/GetList.php
  core/src/Revolution/Processors/Processor.php
  manager/controllers/default/resource/create.class.php
  manager/controllers/default/resource/data.class.php
  manager/controllers/default/resource/staticresource/create.class.php
  manager/controllers/default/resource/staticresource/update.class.php
  manager/controllers/default/resource/symlink/create.class.php
  manager/controllers/default/resource/symlink/update.class.php
  manager/controllers/default/resource/update.class.php
  manager/controllers/default/resource/weblink/create.class.php
  manager/controllers/default/resource/weblink/update.class.php
  manager/controllers/default/search.class.php
  manager/controllers/default/system/dashboards/update.class.php
  manager/controllers/default/system/dashboards/widget/update.class.php
  manager/controllers/default/system/file/create.class.php
  manager/controllers/default/system/file/edit.class.php
  manager/controllers/default/welcome.class.php
Labels: cla-signed

#16026 Add consistent ?mv={version} cache busting suffix to prevent browser cache issues (part two)
  core/src/Revolution/modManagerController.php
Labels: cla-signed

#16001 [3.x] Fix issue where moving resource above another would make the "target" a container.
  core/src/Revolution/Processors/Resource/Sort.php
Labels: cla-signed

#16030 Revert passing script variables by reference
  core/src/Revolution/modScript.php
Labels: urgent, cla-signed

#15979 Increase the specificity for dashboard table CSS rules
  _build/templates/default/sass/_dashboard.scss
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/ready-for-merging, cla-signed

#15964 Improve the regular expression for stripping remaining MODX tags
  core/model/modx/moddashboardwidget.class.php
Labels: bug, pr/review-needed, cla-signed, pr/port-to-3

#15992 [2.x Port] Fix combobox not expanding if processor response is slow
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.combo.js
Labels: pr/review-needed, cla-signed

#16039 Enable to save changed attribute name or container name in the user's extended fields
  manager/assets/modext/widgets/core/modx.orm.js
Labels: pr/ready-for-merging, cla-signed

#16045 Optionally determine context from config.context.php
  .gitignore
  index.php
Labels: pr/ready-for-merging, needs-docs, cla-signed

#16027 Changed brackets for category child elements
  core/src/Revolution/Processors/Element/GetNodes.php
Labels: type-frontend, pr/ready-for-merging, cla-signed

#16057 Correct policy groups description
  core/lexicon/en/policy.inc.php
Labels: area-lexicons, pr/ready-for-merging, cla-signed

#16043 Fix Static File Creation Issue
  core/src/Revolution/Sources/modMediaSource.php
  core/src/Revolution/modElement.php
Labels: cla-signed

#16050 Add explanatory text to create category
  core/lexicon/en/category.inc.php
  core/lexicon/en/default.inc.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/element/modx.tree.element.js
  manager/assets/modext/widgets/windows.js
Labels: type-frontend, pr/ready-for-merging, cla-signed

#15980 [3.x] Fix dates on dashboard feeds in certain locales
  core/src/Revolution/Processors/System/Dashboard/Widget/Feed.php
  manager/assets/modext/widgets/modx.panel.welcome.js
Labels: pr/ready-for-merging, cla-signed

#16052 Changed the order of the fields in Form Customization
  core/model/schema/modx.action.fields.schema.xml
  manager/assets/modext/widgets/fc/modx.panel.fcset.js
Labels: area-fc, pr/ready-for-merging, cla-signed

#16065 Move the existing value of mail_smtp_prefix to mail_smtp_secure
  setup/includes/upgrades/common/3.0.0-update-smtp-system-settings.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
Labels: pr/review-needed, cla-signed

#16069 Stay on the current page after language switch
  core/src/Revolution/modMenu.php
  manager/assets/modext/core/modx.js
  manager/controllers/default/language.class.php
Labels: pr/review-needed, cla-signed

#16051 Call OnFileManagerFileRename if upload_translit changes the name of a new file
  core/src/Revolution/Sources/modMediaSource.php
Labels: pr/review-needed, cla-signed
