Repository modxcms/revolution, pull requests merged in 2022-04, with the labels that each got.

#16012 [Port to 3.x] Fix Various Issues with Form Panel Validation and Field Display - Revised Submission
  _build/templates/default/sass/_forms.scss
  core/lexicon/en/resource.inc.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.panel.js
  manager/assets/modext/widgets/resource/modx.panel.resource.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/ready-for-merging, cla-signed

#16120 Remove outdated lexicon about Google+
  core/lexicon/en/about.inc.php
Labels: pr/ready-for-merging, cla-signed

#16126 Fix inability to create/update user password
  manager/assets/modext/widgets/security/modx.panel.user.js
Labels: urgent, pr/review-needed, cla-signed

#16130 Treat email contents as UTF-8, fixing mangled characters [#16116]
  core/src/Revolution/Mail/modPHPMailer.php
Labels: pr/ready-for-merging, cla-signed

#16132 Fix display of optimize and truncate links in Database Tables panel
  core/src/Revolution/Processors/System/DatabaseTable/mysql/GetList.php
  manager/assets/modext/widgets/system/mysql/modx.grid.databasetables.js
Labels: cla-signed

#16127 Use random hash in tag if element name is blank
  core/src/Revolution/modElement.php
Labels: bug, cla-signed

#16143 Update to xPDO 2.8.4-pl
  core/xpdo/cache/xpdocachemanager.class.php
  core/xpdo/changelog.txt
  core/xpdo/compression/pclzip.lib.php
  core/xpdo/om/xpdoobject.class.php
  core/xpdo/validation/xpdovalidator.class.php
  core/xpdo/xpdo.class.php
Labels: bug, pr/review-needed, cla-signed, dependencies

#15995 Configurable MessageBox minWidth
  manager/assets/modext/core/modx.js
Labels: pr/ready-for-merging, cla-signed

#16142 Fix uncaught TypeError when calling a deprecated method from file
  core/src/Revolution/modX.php
Labels: pr/ready-for-merging, cla-signed

#16112 Fix Setup Error Message Typo
  setup/provisioner/bootstrap.php
Labels: pr/ready-for-merging, cla-signed

#16071 redo 15787 without CS cleanup
  core/model/modx/sources/modfilemediasource.class.php
  core/model/modx/sources/mods3mediasource.class.php
Labels: pr/ready-for-merging, cla-signed

#16149 Adjust placeholder filtering and accessible options for @SELECT
  core/src/Revolution/modTemplateVar.php
  core/src/Revolution/modX.php
Labels: bug, urgent, pr/ready-for-merging, cla-signed

#16146 Update to Smarty 3.1.44
  core/model/smarty/Smarty.class.php
  core/model/smarty/plugins/function.mailto.php
  core/model/smarty/plugins/function.math.php
  core/model/smarty/plugins/modifier.escape.php
  core/model/smarty/plugins/modifiercompiler.escape.php
  core/model/smarty/sysplugins/smarty_internal_templateparser.php
Labels: pr/review-needed, cla-signed

#16147 Ignore E_DEPRECATED and E_STRICT errors in setup
  setup/includes/request/modinstallrequest.class.php
  setup/processors/connector.php
Labels: bug, pr/review-needed, cla-signed

#15912 Fix setStaticElementPath method
  manager/assets/modext/core/modx.js
  manager/assets/modext/widgets/element/modx.panel.chunk.js
  manager/assets/modext/widgets/element/modx.panel.plugin.js
  manager/assets/modext/widgets/element/modx.panel.snippet.js
  manager/assets/modext/widgets/element/modx.panel.template.js
  manager/assets/modext/widgets/element/modx.panel.tv.js
Labels: bug, pr/review-needed, cla-signed, pr/port-to-3

#16118 [Port to 3.x] Fix Various Issues with Form Panel Validation and Field Display - Part 2, TV Panel
  _build/templates/default/sass/_forms.scss
  core/lexicon/en/element.inc.php
  core/lexicon/en/tv.inc.php
  core/model/schema/modx.mysql.schema.xml
  core/src/Revolution/Processors/Element/Create.php
  core/src/Revolution/Processors/Element/Update.php
  core/src/Revolution/mysql/modTemplateVar.php
  manager/assets/modext/widgets/element/modx.panel.tv.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/review-needed, cla-signed

#16119 [Port to 3.x] Fix Various Issues with Form Panel Validation and Field Display - Part 3, Snippet Panel
  core/lexicon/en/snippet.inc.php
  core/src/Revolution/mysql/modSnippet.php
  manager/assets/modext/widgets/element/modx.panel.snippet.js
Labels: pr/review-needed, cla-signed

#16122 [Port to 3.x] Fix Various Issues with Form Panel Validation and Field Display - Part 4, Template Panel
  core/lexicon/en/element.inc.php
  core/lexicon/en/template.inc.php
  core/src/Revolution/mysql/modTemplate.php
  manager/assets/modext/widgets/element/modx.panel.template.js
Labels: pr/review-needed, cla-signed

#16128 [Port to 3.x] Fix Various Issues with Form Panel Validation and Field Display - Part 5, Chunk Panel
  core/lexicon/en/chunk.inc.php
  core/src/Revolution/mysql/modChunk.php
  manager/assets/modext/widgets/element/modx.panel.chunk.js
Labels: pr/review-needed, cla-signed

#16125 [Port to 3.x] Fix Various Issues with Form Panel Validation and Field Display - Part 6, Plugin Panel
  core/lexicon/en/plugin.inc.php
  core/src/Revolution/mysql/modPlugin.php
  manager/assets/modext/widgets/element/modx.panel.plugin.js
Labels: pr/review-needed, cla-signed

#16152 Fix download files from the Media Browser
  core/src/Revolution/Processors/Browser/File/Download.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/media/modx.browser.js
Labels: pr/review-needed, cla-signed

#16151 Don't show the Configuration Check dashboard widget if all checks pass
  manager/templates/default/dashboard/configcheck.tpl
Labels: pr/review-needed, cla-signed

#15865 Skip creation of thumbnails for SVGs
  _build/templates/default/sass/_forms.scss
  core/model/modx/processors/system/phpthumb.class.php
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/review-needed, cla-signed, pr/port-to-3

#16156 Rework concatenated php in lexicon entries
  core/lexicon/en/chunk.inc.php
  core/lexicon/en/snippet.inc.php
  core/lexicon/en/tv.inc.php
  manager/assets/modext/widgets/element/modx.panel.chunk.js
  manager/assets/modext/widgets/element/modx.panel.snippet.js
  manager/assets/modext/widgets/element/modx.panel.tv.js
Labels: pr/review-needed, cla-signed

#16162 [2.x] Make hidden TV's work for weblinks, symlinks and static resources
  manager/templates/default/resource/staticresource/create.tpl
  manager/templates/default/resource/staticresource/update.tpl
  manager/templates/default/resource/symlink/create.tpl
  manager/templates/default/resource/symlink/update.tpl
  manager/templates/default/resource/weblink/create.tpl
  manager/templates/default/resource/weblink/update.tpl
Labels: pr/review-needed, cla-signed

#15840 Add new config option for number TVs
  core/lexicon/en/tv_widget.inc.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/util/utilities.js
  manager/templates/default/element/tv/renders/input/number.tpl
  manager/templates/default/element/tv/renders/inputproperties/number.tpl
Labels: cla-signed, pr/port-to-3

#15833 Fix create button visibility in tree nodes
  _build/templates/default/sass/_tree.scss
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/review-needed, cla-signed

#16165 [3.x] Unit Test for modInputFilter
  _build/test/Tests/Model/Filters/modInputFilterTest.php
Labels: pr/review-needed, cla-signed

#16164 Remove unused lexicon
  core/lexicon/en/configcheck.inc.php
Labels: pr/review-needed, cla-signed

#16161 Normalize the boolean value of the combo property
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.combo.js
  manager/assets/modext/widgets/security/modx.grid.user.group.category.js
  manager/assets/modext/widgets/security/modx.grid.user.group.context.js
  manager/assets/modext/widgets/security/modx.grid.user.group.resource.js
  manager/assets/modext/widgets/security/modx.tree.user.group.js
  manager/assets/modext/widgets/source/modx.grid.source.access.js
Labels: pr/ready-for-merging, cla-signed

#16160 Fix the count in Element/TemplateGetList processor
  core/src/Revolution/Processors/Element/Template/GetList.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.combo.js
  manager/assets/modext/widgets/resource/modx.tree.resource.js
  manager/assets/modext/widgets/resource/modx.window.resource.js
Labels: pr/ready-for-merging, cla-signed

#16163 [3.x] Make hidden TV's work for weblinks, symlinks and static resources
  manager/templates/default/resource/staticresource/create.tpl
  manager/templates/default/resource/staticresource/update.tpl
  manager/templates/default/resource/symlink/create.tpl
  manager/templates/default/resource/symlink/update.tpl
  manager/templates/default/resource/weblink/create.tpl
  manager/templates/default/resource/weblink/update.tpl
Labels: pr/review-needed, cla-signed

#16150 New MODx.util.FileDownload helper method
  core/lexicon/en/file.inc.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/util/utilities.js
Labels: cla-signed

#16106 Make sure file name and line number are included in error messages
  core/src/Revolution/modManagerResponse.php
Labels: pr/review-needed, cla-signed
