Repository modxcms/revolution, pull requests merged in 2023-01, with the labels that each got.

#16347 Add OpenCollective as funding platform in composer.json
  composer.json
Labels: cla-signed

#16342 Add some basic tests for modResource
  _build/test/Tests/Model/Resource/modResourceTest.php
Labels: pr/ready-for-merging, cla-signed

#16337 Fix Custom Property Sets not working after upgrade to MODX 3
  setup/includes/upgrades/common/3.0.3-update-legacy-class-references.php
  setup/includes/upgrades/mysql/3.0.3-pl.php
Labels: pr/ready-for-merging, cla-signed

#16338 Fix issues with TV's Media Sources after upgrading to MODX 3
  setup/includes/upgrades/common/3.0.3-update-legacy-class-references.php
Labels: pr/ready-for-merging, cla-signed

#16089 [3.x] Grid filtering via URL parameters -- Usergroup ACL
  core/src/Revolution/Processors/Element/Template/TemplateVar/GetList.php
  core/src/Revolution/Processors/System/Settings/GetAreas.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/util/utilities.js
  manager/assets/modext/widgets/core/modx.grid.js
  manager/assets/modext/widgets/core/modx.grid.settings.js
  manager/assets/modext/widgets/core/modx.tabs.js
  manager/assets/modext/widgets/element/modx.grid.template.tv.js
  manager/assets/modext/widgets/element/modx.panel.template.js
  manager/assets/modext/widgets/security/modx.grid.user.group.category.js
  manager/assets/modext/widgets/security/modx.grid.user.group.context.js
  manager/assets/modext/widgets/security/modx.grid.user.group.namespace.js
  manager/assets/modext/widgets/security/modx.grid.user.group.resource.js
  manager/assets/modext/widgets/security/modx.grid.user.group.source.js
  manager/assets/modext/widgets/security/modx.panel.groups.roles.js
  manager/assets/modext/widgets/security/modx.panel.user.group.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
  manager/templates/default/css/login-min.css
  manager/templates/default/css/login.css
  setup/assets/css/installer-min.css
  setup/assets/css/installer.css
Labels: pr/ready-for-merging, cla-signed

#16273 Alternate Permissions Combo Fix
  core/src/Revolution/Processors/Model/GetListProcessor.php
  core/src/Revolution/Processors/Security/Access/Permission/GetList.php
  manager/assets/modext/widgets/security/modx.panel.access.policy.template.js
  manager/assets/modext/widgets/system/modx.panel.dashboard.widget.js
Labels: pr/ready-for-merging, cla-signed

#16303 Fix TypeError exceptions when restoring deleted resources
  core/src/Revolution/Processors/Resource/Trash/Restore.php
Labels: pr/ready-for-merging, cla-signed

#16319 Fix Validation Error When Switching TV Types
  manager/assets/modext/widgets/element/modx.panel.tv.js
Labels: pr/ready-for-merging, cla-signed

#16331 Add new error reporting for grids
  _build/templates/default/sass/index.scss
  core/lexicon/en/default.inc.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.grid.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/ready-for-merging, cla-signed

#16321 JavaScript linter: step one
  .eslintrc.js
  package-lock.json
  package.json
Labels: pr/ready-for-merging, cla-signed

#16316 Fix parsing long template tags under some conditions [#16263]
  _build/test/Tests/Model/modParserTest.php
  core/src/Revolution/modParser.php
Labels: area-core, pr/ready-for-merging, cla-signed

#16302 [3.0.2] Fix parsing modifiers when encountering literal brackets
  _build/test/Tests/Model/modParserTest.php
  core/src/Revolution/Filters/modInputFilter.php
Labels: urgent, pr/ready-for-merging, pr/review-needed, cla-signed

#16358 Only post coverage comment when coverage changes.
  codecov.yml
Labels: pr/ready-for-merging, cla-signed

#16364 Fix tab tracking issue for plugin panel
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.grid.js
Labels: pr/ready-for-merging, cla-signed, requires build

#16360 Fix tab tracking error in package manager
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.tabs.js
Labels: urgent, pr/ready-for-merging, cla-signed, requires build

#16354 Fix package manager only ever showing the last version changelog
  manager/assets/modext/workspace/package.grid.js
Labels: pr/ready-for-merging, cla-signed

#16341 Fix "Undefined array key" warnings in modPhpThumb
  core/src/Revolution/modPhpThumb.php
Labels: pr/ready-for-merging, cla-signed, pr/port-to-2

#16328 Prevent OnResourceDelete from Incorrectly Firing on Every Resource Update
  core/src/Revolution/Processors/Resource/Update.php
Labels: pr/ready-for-merging, cla-signed

#16359 Cleanup legacy PHP version references
  core/src/Revolution/Processors/System/ConfigCheck.php
  core/src/Revolution/modPhpThumb.php
  core/src/Revolution/modX.php
  manager/index.php
Labels: pr/ready-for-merging, cla-signed

#16355 Fix and Enhance Usergroup ACL Permissions Grids and Filtering
  core/src/Revolution/Processors/Context/GetList.php
  core/src/Revolution/Processors/Element/Category/GetList.php
  core/src/Revolution/Processors/Security/Access/Policy/GetList.php
  core/src/Revolution/Processors/Security/Access/UserGroup/AccessNamespace/GetList.php
  core/src/Revolution/Processors/Security/Access/UserGroup/Category/GetList.php
  core/src/Revolution/Processors/Security/Access/UserGroup/Context/GetList.php
  core/src/Revolution/Processors/Security/Access/UserGroup/ResourceGroup/GetList.php
  core/src/Revolution/Processors/Security/Access/UserGroup/Source/GetList.php
  core/src/Revolution/Processors/Security/ResourceGroup/GetList.php
  core/src/Revolution/Processors/Source/GetList.php
  core/src/Revolution/Processors/Workspace/PackageNamespace/GetList.php
  manager/assets/modext/widgets/core/modx.grid.js
  manager/assets/modext/widgets/security/modx.grid.user.group.category.js
  manager/assets/modext/widgets/security/modx.grid.user.group.context.js
  manager/assets/modext/widgets/security/modx.grid.user.group.namespace.js
  manager/assets/modext/widgets/security/modx.grid.user.group.resource.js
  manager/assets/modext/widgets/security/modx.grid.user.group.source.js
Labels: pr/ready-for-merging, cla-signed, requires build

#16348 Support multi select in MODx.Browser when multiSelect: true is provided
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.rte.browser.js
  manager/assets/modext/widgets/media/modx.browser.js
Labels: pr/ready-for-merging, cla-signed, requires build

#16349 Remove unnecessary settings for uploaded files
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/src/Revolution/Sources/modMediaSource.php
  manager/assets/modext/widgets/element/modx.panel.tv.js
  setup/includes/upgrades/common/3.0.0-update-sys-setting_upload_files-upload_images.php
  setup/includes/upgrades/common/3.0.0-update-sys-setting_upload_files-woff2.php
  setup/includes/upgrades/common/3.0.0-update-sys-setting_upload_files.php
  setup/includes/upgrades/mysql/3.0.0-pl.php
Labels: area-core, pr/ready-for-merging, cla-signed

#16225 Provide global control to set autocomplete="off"
  manager/assets/modext/core/modx.js
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.searchbar.js
  manager/assets/modext/widgets/resource/modx.panel.resource.js
  manager/assets/modext/widgets/security/modx.panel.user.js
  manager/assets/modext/widgets/system/modx.grid.system.event.js
  manager/templates/default/element/tv/renders/input/autotag.tpl
  manager/templates/default/element/tv/renders/input/email.tpl
  manager/templates/default/element/tv/renders/input/hidden.tpl
  manager/templates/default/element/tv/renders/input/number.tpl
  manager/templates/default/element/tv/renders/input/tag.tpl
  manager/templates/default/element/tv/renders/input/textarea.tpl
  manager/templates/default/element/tv/renders/input/textbox.tpl
  manager/templates/default/element/tv/renders/input/url.tpl
Labels: pr/ready-for-merging, cla-signed, requires build

#16365 Suggest installing the PHP Internationalization extension
  composer.json
Labels: pr/ready-for-merging, cla-signed

#16219 Add filtering for ACL policy and policy template grids
  _build/templates/default/sass/_forms.scss
  _build/templates/default/sass/_xtheme-modx.scss
  core/lexicon/en/policy.inc.php
  manager/assets/modext/widgets/security/modx.panel.access.policy.js
  manager/assets/modext/widgets/security/modx.panel.access.policy.template.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/ready-for-merging, cla-signed, requires build

#15479 Skip files with specified extensions
  core/lexicon/en/source.inc.php
  core/src/Revolution/Sources/modFTPMediaSource.php
  core/src/Revolution/Sources/modFileMediaSource.php
  core/src/Revolution/Sources/modMediaSource.php
  core/src/Revolution/Sources/modS3MediaSource.php
Labels: cla-signed

#16327 Add PHP 8.2 as CI target + minor associated fixes
  .github/workflows/ci.yml
  .github/workflows/phpcs.yml
  composer.json
  core/src/Revolution/Filters/modInputFilter.php
  core/src/Revolution/modLexicon.php
  core/src/Revolution/modX.php
  phpcs.xml
  setup/processors/connector.php
Labels: pr/ready-for-merging, cla-signed

#16361 Add resource alias in template picker as needed
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/resource/modx.window.resource.js
Labels: pr/review-needed, cla-signed, needs-backport, requires build

#16371 Add resource alias in template picker as needed
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/resource/modx.window.resource.js
Labels: cla-signed

#16196 Update uploadObjectsToContainer method
  core/src/Revolution/Sources/modMediaSource.php
Labels: pr/ready-for-merging, cla-signed

#16060 Modify delete and undelete processors to respect syncsite setting
  core/model/modx/processors/resource/create.class.php
  core/model/modx/processors/resource/delete.class.php
  core/model/modx/processors/resource/publish.class.php
  core/model/modx/processors/resource/undelete.class.php
  core/model/modx/processors/resource/unpublish.class.php
  core/model/modx/processors/resource/update.class.php
Labels: pr/review-needed, cla-signed, pr/port-to-3
