Repository modxcms/revolution, pull requests merged in 2023-10, with the labels that each got.

#16478 Add .nvmrc
  _build/templates/default/.nvmrc
Labels: pr/ready-for-merging

#16444 Fix ability to rename content field
  manager/assets/modext/core/modx.js
Labels: pr/ready-for-merging, cla-signed

#16440 Fix deprecation of dynamic properties
  core/src/Revolution/Hashing/modHashing.php
Labels: pr/ready-for-merging, cla-signed

#16401 [3.x] Fixes active tab state for form customization when disabling regions
  manager/assets/modext/core/modx.js
Labels: bug, pr/ready-for-merging, cla-signed

#16438 S3 Speed Up
  core/src/Revolution/Sources/modS3MediaSource.php
Labels: pr/ready-for-merging, cla-signed

#16410 Fix PHP Fatal error: Cannot declare class modTemplateVarInputRenderText
  core/src/Revolution/modTemplateVar.php
Labels: bug, pr/review-needed, cla-signed

#16473 Fix ability to view Manager Actions
  manager/controllers/default/system/logs/index.class.php
Labels: bug, cla-signed

#16460 Hopefully fixed recently edited resources (sub)query
  core/src/Revolution/Processors/Security/User/GetRecentlyEditedResources.php
Labels: bug, cla-signed
