Repository modxcms/revolution, pull requests merged in 2023-08, with the labels that each got.

#16462 fix return type GetProcessor.php
  core/src/Revolution/Processors/Model/GetProcessor.php
Labels: cla-signed

#16451 Changed the order of variables in config.inc.php
  core/docs/config.inc.tpl
Labels: area-core, proposal, pr/ready-for-merging

#16449 Added names of elements in context menu
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/system/modx.tree.directory.js
Labels: type-frontend, pr/ready-for-merging, cla-signed

#16443 Only assign user if instance of modX in modAccessibleObject::checkPolicy
  core/src/Revolution/modAccessibleObject.php
Labels: bug, area-setup, pr/ready-for-merging, cla-signed, needs-backport

#16435 Update subMenuBuilder so "installer-entry" is always at the top [v3.x]
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/src/Revolution/modMenu.php
Labels: pr/ready-for-merging, cla-signed

#16433 Avoid errors and incorrect listings in Trash Manager
  core/src/Revolution/Processors/Resource/Trash/GetList.php
Labels: pr/ready-for-merging, cla-signed

#16431 Add namespaces partition to cache refresh process
  core/src/Revolution/Processors/System/ClearCache.php
  core/src/Revolution/modCacheManager.php
Labels: bug, area-core, urgent, pr/ready-for-merging, cla-signed

#16414 Settings grid adjustments for Extras support
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/util/utilities.js
  manager/assets/modext/widgets/core/modx.grid.settings.js
  manager/assets/modext/widgets/core/modx.tabs.js
Labels: pr/ready-for-merging, cla-signed, requires build
