Repository modxcms/revolution, pull requests merged in 2024-08, with the labels that each got.

#16596 Fix max parser iterations for resources without a template
  core/src/Revolution/modResource.php
Labels: bug, urgent

#16582 Add secondary regex option for transliterated file uploads
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/src/Revolution/Sources/modMediaSource.php
Labels: pr/review-needed, requires build

#16522 Fix issues with extending modSessionHandler and flushing all sessions
  core/src/Revolution/Processors/Security/Flush.php
  core/src/Revolution/modSessionHandler.php
  core/src/Revolution/modX.php
Labels: area-core

#16579 Reveal current username in main menu bar (User menu)
  _build/templates/default/sass/_navbar.scss
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/ready-for-merging, requires build

#16599 Fixed tree of elements in property sets
  core/src/Revolution/Processors/Element/PropertySet/GetNodes.php
Labels: type-frontend, pr/ready-for-merging

#16578 Support dot followed by space in directories
  core/src/Revolution/Processors/Browser/Browser.php
Labels: pr/review-needed

#16529 Fix grouping grid sorting - ACL grids
  .eslintrc.js
  core/src/Revolution/Processors/Model/GetListProcessor.php
  core/src/Revolution/Processors/Security/Access/UserGroup/AccessNamespace/GetList.php
  core/src/Revolution/Processors/Security/Access/UserGroup/Category/GetList.php
  core/src/Revolution/Processors/Security/Access/UserGroup/Context/GetList.php
  core/src/Revolution/Processors/Security/Access/UserGroup/ResourceGroup/GetList.php
  core/src/Revolution/Processors/Security/Access/UserGroup/Source/GetList.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/core/modx.grid.js
  manager/assets/modext/widgets/security/modx.grid.user.group.base.js
  manager/assets/modext/widgets/security/modx.grid.user.group.category.js
  manager/assets/modext/widgets/security/modx.grid.user.group.context.js
  manager/assets/modext/widgets/security/modx.grid.user.group.namespace.js
  manager/assets/modext/widgets/security/modx.grid.user.group.resource.js
  manager/assets/modext/widgets/security/modx.grid.user.group.source.js
Labels: pr/review-needed
