Repository modxcms/revolution, pull requests merged in 2024-03, with the labels that each got.

#16477 Fix sanity check in resource/create controller
  manager/controllers/default/resource/create.class.php
Labels: pr/ready-for-merging, pr/port-to-3

#16527 Fix default value for modManagerLog.occurred column
  core/model/modx/mysql/modmanagerlog.map.inc.php
  core/model/schema/modx.mysql.schema.xml
  setup/includes/upgrades/mysql/2.8.7-pl.php
Labels: bug, pr/ready-for-merging

#16505 Fix saving time for date TVs created in MODX 2.x
  core/src/Revolution/Processors/Resource/Create.php
  core/src/Revolution/Processors/Resource/Update.php
Labels: pr/ready-for-merging

#16467 Add guard-clause to clearDirty method
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/util/utilities.js
Labels: bug, blocked

#16493 Fix Element handling from within Categories tree
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/element/modx.tree.element.js
Labels: blocked

#16498 Trim context setting keys on creation
  core/model/modx/processors/context/setting/create.class.php
Labels: bug, pr/ready-for-merging

#16448 Add session garbage collector check
  setup/includes/test/modinstalltest.class.php
  setup/lang/en/default.inc.php
  setup/lang/en/test.inc.php
Labels: area-core, area-setup, pr/ready-for-merging, cla-signed

#16479 Improve file system error feedback
  core/lexicon/en/file.inc.php
  core/src/Revolution/Sources/modMediaSource.php
Labels: pr/ready-for-merging

#16489 Fix Element handling from within Categories tree
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/widgets/element/modx.tree.element.js
Labels: pr/ready-for-merging

#16500 Trim context setting keys on creation
  core/src/Revolution/Processors/Context/Setting/Create.php
Labels: pr/ready-for-merging

#16515 Add missing system setting for profile photo media source
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
Labels: pr/ready-for-merging

#16526 Fix default value for modManagerLog.occurred column
  core/model/schema/modx.mysql.schema.xml
  core/src/Revolution/mysql/modManagerLog.php
  setup/includes/upgrades/common/3.0.5-db-changes.php
  setup/includes/upgrades/mysql/3.0.5-pl.php
Labels: bug

#16447 Add reloading of lexicon entries for any namespace
  core/lexicon/en/lexicon.inc.php
  core/src/Revolution/Processors/Workspace/Lexicon/ReloadFromBase.php
  manager/assets/modext/workspace/lexicon/lexicon.grid.js
Labels: area-lexicons, pr/review-needed, cla-signed
