Repository modxcms/revolution, pull requests merged in 2024-09, with the labels that each got.

#16610 3.x Fix TV Category not found issue in Template and TV editing panels
  .eslintrc.js
  manager/assets/modext/widgets/element/modx.grid.template.tv.js
  manager/assets/modext/widgets/element/modx.grid.tv.template.js
  manager/assets/modext/widgets/element/modx.panel.template.js
  manager/assets/modext/widgets/element/modx.panel.tv.js
Labels: urgent, pr/review-needed

#16555 Form Customization: Fully support comma-separated constraints lists
  core/lexicon/en/formcustomization.inc.php
  core/src/Revolution/Processors/Security/Forms/Set/Create.php
  core/src/Revolution/Processors/Security/Forms/Set/Update.php
  core/src/Revolution/Processors/Security/Forms/Set/UpdateFromGrid.php
  core/src/Revolution/modManagerController.php
  core/src/Revolution/modTemplateVar.php
  manager/assets/modext/modx.jsgrps-min.js
  manager/assets/modext/util/utilities.js
  manager/assets/modext/widgets/core/modx.grid.js
  manager/assets/modext/widgets/fc/modx.grid.fcset.js
  manager/assets/modext/widgets/fc/modx.panel.fcset.js
  manager/controllers/default/security/forms/set/update.class.php
Labels: pr/review-needed, requires build

#16521 Update generate password logic to use proper methods
  core/src/Revolution/modUser.php
Labels: area-security, pr/review-needed

#16602 Fix manager messages grid permissions and other improvements
  _build/templates/default/sass/_forms.scss
  _build/templates/default/sass/index.scss
  manager/assets/modext/widgets/security/modx.grid.message.js
  manager/templates/default/css/index-min.css
  manager/templates/default/css/index.css
Labels: pr/review-needed, requires build

#16615 Fix error suppression for PHP 8+
  core/src/Revolution/Error/modErrorHandler.php
Labels: bug, area-core, pr/port-to-2

#16608 Fix Dashboard Updates widget's display of the most recent modx version
  core/src/Revolution/Processors/SoftwareUpdate/Base.php
  core/src/Revolution/Processors/SoftwareUpdate/GetFile.php
  core/src/Revolution/Processors/SoftwareUpdate/GetList.php
  manager/controllers/default/dashboard/widget.updates.php
  manager/controllers/default/welcome.class.php
  manager/templates/default/dashboard/updates.tpl
Labels: pr/review-needed, needs-backport

#16621 Update Minimum PHP Version in phpcs.xml
  phpcs.xml
Labels: pr/review-needed

#16620 Fix User Date of Birth Validation and Processing
  core/src/Revolution/Processors/Security/Profile/Update.php
  core/src/Revolution/Processors/Security/User/Validation.php
Labels: pr/review-needed
