Repository modxcms/revolution, pull requests merged in 2024-02, with the labels that each got.

#16381 Add some basic tests for modRestService
  _build/test/Tests/Model/Rest/modRestServiceTest.php
  _build/test/data/rest/Controllers/Index.php
  _build/test/data/rest/Controllers/Uninstantiable.php
  _build/test/phpunit.xml
Labels: pr/review-needed, cla-signed

#16475 Make “root” a reserved (restricted) key for Contexts
  core/lexicon/en/context.inc.php
  core/src/Revolution/Processors/Context/Create.php
  core/src/Revolution/Processors/Context/GetList.php
  core/src/Revolution/modContext.php
Labels: pr/ready-for-merging

#14482 Update subMenuBuilder so "installer-entry" is always at the top
  _build/data/transport.core.system_settings.php
  core/lexicon/en/setting.inc.php
  core/model/modx/modmenu.class.php
Labels: bug, area-setup, blocked, pr/ready-for-merging, cla-signed

#16415 Fix Trash Manager infinite loading error
  core/model/modx/processors/resource/trash/getlist.class.php
Labels: pr/ready-for-merging, cla-signed

#16482 [2.x] Remove deprecation warning during setup for PHP 8.2
  setup/includes/modinstalllexicon.class.php
Labels: pr/ready-for-merging

#16506 Update phpThumb to v1.7.22-202312071641
  core/model/phpthumb/phpthumb.class.php
Labels: bug, urgent, pr/ready-for-merging, dependencies
